/* Server-authoritative play and original SVG illustration. */
(() => {
'use strict';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',tile=30,storageKey='downtown-local-room-v1';
const statLabels={knowledge:'ความรู้',wealth:'การเงิน',happiness:'ความสุข',health:'สุขภาพ'};
const transports={walk:['🚶','เดินเท้า'],bus:['🚌','รถเมล์'],moto:['🛵','วินมอเตอร์ไซค์'],taxi:['🚕','แท็กซี่'],car:['🚙','รถส่วนตัว']};
const labels={black_market:'ตลาดมืด',home:'อพาร์ตเมนต์',condo:'คอนโด',school:'โรงเรียน',university:'มหาวิทยาลัย',hospital:'โรงพยาบาล',bank:'ธนาคาร',market:'ตลาดริมคลอง',convenience:'ร้านสะดวกซื้อ',job_center:'สำนักงานจัดหางาน',mall:'ห้างสรรพสินค้า',restaurant:'ร้านอาหาร',fitness:'ฟิตเนส',automotive:'ศูนย์ยานยนต์',ticket_venue:'โรงหนังและกิจกรรม',hangout:'Hang out',casino:'กาสิโน',city_exit:'ออกสู่ชนบท'};
const symbols={sleep:'☾',full_rest:'☾',emergency_rest:'✚',study:'▤',choose_track:'▤',work:'⚒',apply_job:'✉',activity:'✦',casino:'♠',bank:'฿',form_partnership:'♡',draw_card:'▰',buy_car:'🚙'};
let socket,state=null,requestPending=false,animating=false,selected='',selectedTransport='walk',lastPresentation='',queue=[],noticeTimer,resultsShown=false,tabReplaced=false;
let motionOff=localStorage.getItem('downtown-motion-off')==='1';
const art=()=>window.DowntownArt;
const el=(tag,cls='',value)=>{const n=document.createElement(tag);n.className=cls;if(value!==undefined)n.textContent=String(value);return n;};
const svg=(tag,attrs={})=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n;};
const svgt=(parent,x,y,value,attrs={})=>{const n=svg('text',{x,y,...attrs});n.textContent=value;parent.append(n);return n;};
const amount=value=>new Intl.NumberFormat('th-TH',{maximumFractionDigits:2}).format(Number(value)||0),money=value=>amount(value)+' ฿';
const me=()=>state?.players.find(p=>p.id===state.you.id),active=()=>state?.players.find(p=>p.id===state.activePlayerId);
const myTurn=()=>state?.status==='playing'&&state.you.id===state.activePlayerId,busy=()=>requestPending||animating,locations=()=>state?.map?.locations||[];
const at=p=>({x:(p.x+.5)*tile,y:(p.y+.5)*tile}),points=path=>path.map(p=>{const c=at(p);return c.x+','+c.y;}).join(' ');
const reduced=()=>motionOff||matchMedia('(prefers-reduced-motion: reduce)').matches;
const avatar=p=>{const h=el('span');h.innerHTML=art().avatar(p.color,state.players.indexOf(p));return h.firstElementChild;};
function button(text,cls,fn,disabled=false){const b=el('button',cls,text);b.type='button';b.disabled=disabled;b.addEventListener('click',e=>{if(b.dataset.action==='study_degree'||/เรียน|Study/.test(b.textContent))activityBurst(b,'📚');else if(/Working|^Work/.test(b.textContent))activityBurst(b,'⚒');fn(e);});return b;}
function activityBurst(button,icon){if(reduced())return;const rect=button.getBoundingClientRect(),host=button.closest('dialog')||document.body;for(let i=0;i<7;i++){const particle=el('span','activity-particle',icon==='⚒'?['⚒','📄','🪙'][i%3]:icon);particle.setAttribute('aria-hidden','true');particle.style.left=(rect.left+rect.width/2)+'px';particle.style.top=(rect.top+rect.height/2)+'px';host.append(particle);animateElement(particle,[{transform:'translate(-50%,-50%) scale(.5)',opacity:1},{transform:`translate(${(i-3)*32}px,${-55-Math.sin(i)*30}px) rotate(${(i-3)*24}deg) scale(1.2)`,opacity:0}],{duration:650,easing:'ease-out'}).finally(()=>particle.remove());}}
function notice(message,success=false){clearTimeout(noticeTimer);$('notice').textContent=message;$('notice').className='notice'+(success?' success':'');$('notice').hidden=false;noticeTimer=setTimeout(()=>$('notice').hidden=true,4500);}
function readRoom(){try{return JSON.parse(localStorage.getItem(storageKey)||'null');}catch{return null;}}
function saveRoom(room){localStorage.setItem(storageKey,JSON.stringify({roomCode:room.roomCode,playerId:room.playerId||room.you?.id}));}
function returnToLanding(message){
 const player=me();if(player)$('player-name').value=player.name;
 localStorage.removeItem(storageKey);state=null;queue=[];lastPresentation='';resultsShown=false;selected='';requestPending=false;
 $('info-dialog').close();$('location-panel').hidden=true;$('scene-overlay').hidden=true;$('game-view').classList.remove('night');setHand(false);render();
 $('player-name').focus({preventScroll:true});if(message)notice(message,true);
}
async function leaveRoom(){
 if(!state||!['lobby','finished'].includes(state.status)||busy()||!socket?.connected)return;
 const host=state.you.host;requestPending=true;$('info-dialog').close();renderLobby();
 try{const reply=await socket.timeout(7000).emitWithAck('room:leave',{});if(!reply.ok)notice(reply.error);else if(state)returnToLanding(host&&state.status==='lobby'?'ยกเลิกห้องแล้ว สร้างห้องใหม่ได้เลย':'ออกจากห้องแล้ว');}
 catch{notice('ออกจากห้องไม่ได้ กรุณาลองอีกครั้งเมื่อเชื่อมต่อแล้ว');}
 finally{requestPending=false;render();}
}
function askToLeave(){
 if(!state||state.status!=='lobby'||busy())return;
 if(!state.you.host||state.players.length===1)return leaveRoom();
 const content=el('div');content.append(el('h2','','ยกเลิกห้องนี้?'),el('p','','เพื่อนในห้องจะกลับไปหน้าเริ่มต้นพร้อมกัน และรหัสห้องนี้จะใช้ไม่ได้'),button('Exit · ยกเลิกห้อง','exit-button',leaveRoom),button('กลับไปห้อง','subtle',()=>$('info-dialog').close()));openInfo(content);
}
function connection(text,offline=false){$('connection-status').textContent=text;$('connection-status').className='connection-status'+(offline?' offline':'');}
function action(type,payload={}){return perform('game:action',{type,payload});}
async function perform(event,payload){
 if(busy()||!socket?.connected)return;if(event==='game:action'||event==='game:travel')payload={...payload,expectedVersion:state.version};requestPending=true;for(const b of $('info-content').querySelectorAll('button'))b.disabled=true;renderHUD();renderCards();if(selected)renderLocation();
 try{const ack=await socket.timeout(7000).emitWithAck(event,payload);if(!ack?.ok)notice(translateError(ack?.error||'ทำรายการไม่ได้'));}
 catch{notice('ยังไม่ได้รับคำตอบจากเมือง กรุณารอสักครู่แล้วลองใหม่');}
 finally{requestPending=false;renderHUD();renderCards();if(selected)renderLocation();if($('info-dialog').open){const status=el('p','panel-note','อัปเดตแล้ว · ปิดหน้าต่างด้วยปุ่ม × เมื่อพร้อม');$('info-content').append(status);}}
}
function translateError(text){return({'It is not your turn':'ยังไม่ถึงตาคุณ','Action is unavailable now':'กิจกรรมนี้ยังทำไม่ได้ ลองเลือกใหม่','Already at destination':'คุณอยู่ที่นี่แล้ว','A car is required':'ต้องมีรถส่วนตัวก่อน','Finish choosing cards to discard first':'เลือกการ์ดที่จะทิ้งให้ครบก่อน'})[text]||text;}
function render(){
 $('landing-view').hidden=!!state;$('waiting-view').hidden=!state||state.status!=='lobby';$('game-view').hidden=!state||state.status==='lobby';$('room-menu').hidden=!state;
 if(!state)return;if(state.status==='lobby')renderLobby();else{renderHUD();if(!animating)renderMap();renderCards();if(selected)renderLocation();if(state.status==='finished'&&!resultsShown&&!animating&&!queue.length){resultsShown=true;setTimeout(showResults,100);}}
}
function renderLobby(){
 $('waiting-code').textContent=state.roomCode;$('waiting-art').innerHTML=art().actionScene('apply_job');$('waiting-players').replaceChildren();
 for(const p of state.players){const cell=el('div','waiting-player');cell.append(avatar(p),el('strong','',p.name),el('small','',p.id===state.you.id?'คุณ':'ชาวเมือง'));$('waiting-players').append(cell);}
 $('start-game').hidden=!state.you.host;$('start-game').disabled=busy()||!state.singlePlayer&&state.players.length<2;$('waiting-message').textContent=state.you.host?(state.singlePlayer?'Single player · เริ่มได้เลย':'แชร์รหัสห้องให้เพื่อน แล้วเริ่มเมื่อพร้อม'):'รอโฮสต์เริ่มเกม';
 $('exit-room').textContent=state.you.host?'Exit · ยกเลิกห้อง':'Exit · ออกจากห้อง';$('exit-room').disabled=busy()||!socket?.connected;
}
function renderHUD(){
 if(!state||state.status==='lobby')return;const p=me();if(!p)return;
 const sum=$('self-summary');sum.replaceChildren();const heading=el('div','self-heading'),text=el('div');text.append(el('strong','',p.name),el('small','',myTurn()?'ถึงตาของคุณ':'ชาวเมืองของคุณ'));heading.append(avatar(p),text);sum.append(heading,el('div','cash-row',money(p.cash)),el('div','net-row','สุทธิ '+money(p.netSavings)+' / '+money(state.goal)));
 const ap=el('div','ap-row');ap.append(el('small','','เวลาที่เหลือ'),el('strong','',amount(p.ap)+' AP'));sum.append(ap);
 sum.append(el('div','sleep-pill'+(p.sleepAp<4?' warning':''),(p.sleepAp>=4?'☾ นอนครบแล้ว':'☾ นอน '+amount(p.sleepAp)+'/4 AP')+(p.hasEaten?' · กินแล้ว':' · ยังไม่กิน')));
 if(p.phaseNotices?.length)sum.append(el('small','phase-notices',p.phaseNotices.join(' · ')));
 const bars=$('stats-bars');if(!bars.children.length)for(const[key,label]of Object.entries(statLabels)){const row=el('div','stat-row');row.dataset.stat=key;const top=el('div','stat-top');top.append(el('span','',label),el('b'));const track=el('div','stat-track');track.append(el('div','stat-fill'));row.append(top,track);bars.append(row);}
 for(const row of bars.children){const value=p.stats[row.dataset.stat];row.querySelector('b').textContent=amount(value);row.querySelector('.stat-fill').style.width=Math.max(0,Math.min(100,value))+'%';}
 const a=active()||p;$('turn-avatar').replaceChildren(avatar(a));const turn=state.week;
 $('turn-label').textContent=state.status==='finished'?'จบเรื่องราวในเมือง':'Turn '+turn;
 $('phase-label').textContent='Phase '+(state.phase==='workday'?1:2)+'/2';$('active-name').textContent=a.name+(myTurn()?' (คุณ)':'')+(p.custody?' · ควบคุมตัว':'');
 $('end-phase').disabled=!myTurn()||busy()||!!state.deck?.pendingDiscard;$('end-phase').textContent=state.status==='finished'?'ดูอันดับ':'จบช่วง →';if(state.status==='finished')$('end-phase').disabled=false;
 $('deck-count').textContent=state.deck.remaining+'/'+state.deck.size;
 const jobs=[p.mainJobId,p.parttimeJobId].filter(Boolean).map(id=>state.catalog.careers.find(j=>j.id===id));$('working-button').hidden=!jobs.length;$('working-button').disabled=!myTurn()||busy()||p.custody;$('working-button').title=jobs.map(j=>j.name).join(' / ');
 const refillTarget=state.deck?.refillToHandSize??5;const handLeft=refillTarget-state.hand.length;
 $('map-tip').textContent=state.deck?.pendingDiscard?'เลือกการ์ดในมือเพื่อทิ้งอีก '+state.deck.pendingDiscard.count+' ใบ':!myTurn()?'รอ '+a.name+' · เลือกอาคารเพื่อดูสถานที่ได้':state.phase==='weekend'&&handLeft>0?'จบ Weekend → จั่วเติมมืออีก '+handLeft+' ใบ · เลือกอาคารเพื่อเล่น':'เลือกอาคารเพื่อเล่นหรือจบ Phase';
 $('seasonal-banner').hidden=!state.seasonal;if(state.seasonal)$('seasonal-banner').textContent='✦ '+state.seasonal.name+' · '+state.seasonal.remaining+' สัปดาห์';
 $('rivals').replaceChildren();for(const other of state.players){const b=button('','rival'+(other.id===state.activePlayerId?' active':''),()=>showPlayer(other));b.dataset.player=other.id;b.title=other.name+(other.connected?'':' · ออฟไลน์');b.setAttribute('aria-label','ดูสถานะ '+other.name);b.append(avatar(other));const dot=el('i','rival-dot');if(!other.connected)dot.style.background='#aaa';b.append(dot);$('rivals').append(b);}document.body.classList.toggle('reduce-motion',motionOff);
}
function cardTheme(card){if(card.effect?.drawCount)return['#c4d8bd','↻','แลกการ์ด'];if(card.kind==='passive')return['#c8d9d2','♡','ต่อเนื่อง'];if(card.effect?.cash||card.effect?.monthlyIncome||card.effect?.weeklyIncome)return['#ebcf93','฿','โอกาส'];if(card.effect?.experience)return['#bbd3dc','⚒','ประสบการณ์'];if(card.effect?.knowledge)return['#bbd3dc','▤','ทักษะ'];if(card.effect?.carOwnership||card.effect?.travelDiscount)return['#c8c2db','➜','เดินทาง'];return['#e9c1ad','✦','ชีวิต'];}
function renderCards(){
 if(!state||state.status==='lobby')return;$('hand-count').textContent=state.hand.length;const phint=state.deck.pendingDiscard?'เลือกทิ้ง '+state.deck.pendingDiscard.count+' ใบ':state.hand.length>0?'เลือกการ์ดเพื่อดูและใช้':'มือว่าง · กองจั่วจะเติมมือให้ครบ '+(state.deck?.refillToHandSize??5)+' ใบเมื่อจบ Weekend';$('hand-hint').textContent=phint;$('hand-list').replaceChildren();
 state.hand.forEach((card,index)=>{const[color,symbol,kind]=cardTheme(card),b=button('','hand-card',()=>showCard(index),busy());b.dataset.cardIndex=index;b.style.setProperty('--card-color',color);b.style.setProperty('--tilt',((index-(state.hand.length-1)/2)*3)+'deg');b.style.setProperty('--lift',(Math.abs(index-(state.hand.length-1)/2)*2)+'px');b.title=card.name;b.setAttribute('aria-label',(state.deck.pendingDiscard?'เลือกทิ้ง ':'ดูการ์ด ')+card.name);const picture=el('div','card-picture');picture.innerHTML=art().actionScene(card.effect?.experience?'work':card.effect?.knowledge?'study':card.effect?.drawCount?'draw_card':card.effect?.cash?'work':card.effect?.carOwnership?'buy_car':'play_card');b.append(picture,el('span','card-kind',kind+(card.kind==='passive'?' · PASSIVE':' · ACTIVE')),el('strong','',card.name),el('small','','1 AP · '+money(card.cost)));$('hand-list').append(b);});
 if(!state.hand.length)$('hand-list').append(el('small','','มือว่าง · กองจั่วจะเติมมือครบ '+(state.deck?.refillToHandSize??5)+' ใบเมื่อจบ Weekend ของคุณ'));
}
function showCard(index){
 const card=state.hand[index];if(!card)return;const[color,symbol,kind]=cardTheme(card),content=el('div');content.append(el('span','eyebrow',kind+' · '+card.kind.toUpperCase()),el('h2','',card.name));const picture=el('div','card-detail-art');picture.style.setProperty('--card-color',color);picture.innerHTML=art().actionScene(card.effect?.experience?'work':card.effect?.knowledge?'study':card.effect?.drawCount?'draw_card':card.effect?.cash?'work':'play_card');content.append(picture,el('p','',card.description));
 for(const[key,value]of Object.entries(card.effect||{})){const names={...statLabels,cash:'เงิน',ap:'AP',weeklyIncome:'ปันผล/Turn',experience:'ประสบการณ์',monthlyIncome:'รายได้/เดือน',travelDiscount:'ส่วนลดเดินทาง',eventShield:'กันเหตุการณ์',carOwnership:'รถส่วนตัว',partnerToken:'หุ้นส่วน',drawCount:'จั่ว',discardCount:'ทิ้ง'};content.append(el('span','card-effect',(names[key]||key)+' '+(typeof value==='number'&&value>0?'+':'')+amount(value)));}
 content.append(el('p','card-cost','ใช้ 1 AP'+(card.cost?' · '+money(card.cost):'')+(card.monthlyFee?' · ต่ออายุ '+money(card.monthlyFee)+'/เดือน':'')));if(card.playAt)content.append(el('p','panel-note','ใช้ได้ที่ '+labels[card.playAt]));
 const type=state.deck.pendingDiscard?'discard_card':'play_card',allowed=state.actions.find(a=>a.type===type&&a.payload.index===index);content.append(button(state.deck.pendingDiscard?'ทิ้งใบนี้ →':'ใช้การ์ด →','primary',()=>action(type,allowed.payload),!allowed||busy()));if(!allowed)content.append(el('p','panel-note',myTurn()?'ยังใช้ไม่ได้: ตรวจ AP เงิน สถานที่ หรือจำนวนการ์ดในมือ':'เก็บแผนไว้ก่อน ยังไม่ถึงตาคุณ'));openInfo(content);
}
function pathLine(parent,path,attrs={}){if(path?.length)parent.append(svg('polyline',{points:points(path),fill:'none',...attrs}));}
function renderMap(){
 const canvas=$('city-map'),map=state.map;canvas.replaceChildren();canvas.setAttribute('viewBox',`-45 -70 ${map.width*tile+90} ${map.height*tile+110}`);canvas.setAttribute('preserveAspectRatio','xMidYMid meet');const deco=map.decorative||{},base=svg('g');
 // Soft park patches and canals, without a visible tile grid.
 for(const park of deco.parks||[]){const c=at(park);base.append(svg('rect',{x:c.x-15,y:c.y-15,width:park.width*tile,height:park.height*tile,rx:45,fill:'#d0ddb8',opacity:.65}));}
 const river=deco.river;if(river?.points){pathLine(base,river.points,{class:'map-road',stroke:'#b4c9b4','stroke-width':river.width*tile+10});pathLine(base,river.points,{class:'map-road',stroke:'#aad5d0','stroke-width':river.width*tile});pathLine(base,river.points,{class:'map-road',stroke:'#d3e8db','stroke-width':2,'stroke-dasharray':'15 30'});}
 for(const plaza of deco.plazas||[]){const c=at(plaza);base.append(svg('ellipse',{cx:c.x,cy:c.y,rx:plaza.radius*tile,ry:plaza.radius*tile*.7,fill:'#dbcdb0',stroke:'#c1b59e','stroke-width':3}));}canvas.append(base);
 const scenery=svg('g');const occupied=(x,y)=>locations().some(l=>Math.hypot(l.x-x,l.y-y)<2.5)||map.roads.some(r=>(r[0]===r[2]&&Math.abs(x-r[0])<1&&y>=Math.min(r[1],r[3])&&y<=Math.max(r[1],r[3]))||(r[1]===r[3]&&Math.abs(y-r[1])<1&&x>=Math.min(r[0],r[2])&&x<=Math.max(r[0],r[2])));
 for(let i=0;i<88;i++){const x=1+((i*17+3)%37),y=1+((i*11+5)%26);if(occupied(x,y))continue;const c=at({x,y}),g=svg('g',{transform:`translate(${c.x} ${c.y})`,opacity:.75});
 if(i%3===0)g.innerHTML='<path d="M0 0v-18" stroke="#8c9277" stroke-width="3"/><ellipse cy="-20" rx="12" ry="16" fill="#aabd8f" stroke="#91aa83" stroke-width="1.5"/><ellipse cx="-6" cy="-14" rx="8" ry="10" fill="#b9c995"/>';
 else g.innerHTML='<rect x="-17" y="-23" width="34" height="25" rx="3" fill="'+['#e8d9bc','#ddcfc1','#d9dcc7'][i%3]+'" stroke="#b7b5a1" stroke-width="1.5"/><path d="M-20 -23L-9 -33H12L20 -23Z" fill="'+['#c89885','#c5ae91','#bda5a0'][i%3]+'" stroke="#b1a08c"/><rect x="-10" y="-17" width="7" height="9" rx="1" fill="#b6cccc"/><rect x="5" y="-17" width="7" height="9" rx="1" fill="#b6cccc"/>';scenery.append(g);}canvas.append(scenery);
 const roads=svg('g');for(const r of map.roads){const a=at({x:r[0],y:r[1]}),b=at({x:r[2],y:r[3]}),d=`M${a.x} ${a.y}L${b.x} ${b.y}`;roads.append(svg('path',{d,class:'map-road',stroke:'#a8a99a','stroke-width':22}),svg('path',{d,class:'map-road',stroke:'#bdc0af','stroke-width':17}),svg('path',{d,class:'map-road',stroke:'#ece7cf','stroke-width':1.5,'stroke-dasharray':'7 14'}));}canvas.append(roads);
 for(const landmark of deco.landmarks||[]){const c=at(landmark);if(landmark.kind==='temple'){const g=svg('g',{transform:`translate(${c.x} ${c.y})`});g.innerHTML='<rect x="-22" y="-30" width="44" height="30" rx="3" fill="#ede0b9" stroke="#c4b18b"/><path d="M-27 -30L0 -60L27 -30ZM-18 -45L0 -67L18 -45" fill="#d6b07c" stroke="#bda076" stroke-width="2"/><rect x="-5" y="-22" width="10" height="22" fill="#c0a783"/>';canvas.append(g);}else svgt(canvas,c.x,c.y,landmark.name||'',{'font-size':10,fill:'#88a197','text-anchor':'middle'});}
 const zoneAnchors=[{x:7,y:1},{x:27,y:0},{x:3,y:19},{x:30,y:10},{x:9,y:27},{x:28,y:26}];map.zones.forEach((zone,i)=>{const c=at(zoneAnchors[i]);svgt(canvas,c.x,c.y,zone.name,{'font-size':13,fill:'#99a082','text-anchor':'middle','font-weight':600});});
 const route=state.travelOptions?.[selected]?.find(t=>t.transport===selectedTransport);if(route)pathLine(canvas,route.path,{class:'map-route'});
 for(const stop of map.busStops||[]){const c=at(stop),g=svg('g',{transform:`translate(${c.x+15} ${c.y+12})`});g.append(svg('rect',{x:-5,y:-8,width:10,height:11,rx:3,fill:'#91b8be',stroke:'#758f94','stroke-width':1.5}));svgt(g,0,0,'B',{'text-anchor':'middle','font-size':7,fill:'#fffaf0'});canvas.append(g);}
 for(const location of locations()){const c=at(location),closed=!location.openPhases.includes(state.phase),g=svg('g',{class:'map-location'+(selected===location.id?' selected':'')+(closed?' closed':''),transform:`translate(${c.x} ${c.y})`,tabindex:0,role:'button','aria-label':'เลือก '+labels[location.id],'data-location':location.id});g.append(svg('ellipse',{cx:0,cy:-1,rx:55,ry:19,class:'location-ring'}));const building=svg('g',{class:'building-art'});building.innerHTML=art().building(location.id);g.append(building);svgt(g,0,22,labels[location.id],{'text-anchor':'middle',class:'location-label'});const title=svg('title');title.textContent=location.name+(closed?' · ปิดช่วงนี้':'');g.append(title);g.addEventListener('click',()=>chooseLocation(location.id));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseLocation(location.id);}});canvas.append(g);}
 const occupants=new Map();for(const p of state.players.filter(p=>p.id===state.activePlayerId)){const c=at(p.position),key=p.position.x+','+p.position.y,n=occupants.get(key)||0;occupants.set(key,n+1);const g=svg('g',{class:'player-token','data-player':p.id,transform:`translate(${c.x+n*18-8} ${c.y+4})`});g.append(svg('ellipse',{cx:0,cy:0,rx:17,ry:8,class:'token-halo',stroke:p.color,opacity:.9}));const body=svg('g');body.innerHTML=art().token(p.color,state.players.indexOf(p));g.append(body);svgt(g,0,15,p.name,{'text-anchor':'middle',class:'token-name'});canvas.append(g);}
}
function setHand(expanded){document.querySelector('.hand-area').classList.toggle('collapsed',!expanded);$('hand-toggle').setAttribute('aria-expanded',String(expanded));}
function chooseLocation(id){if(animating)return;setHand(false);selected=id;selectedTransport=state.travelOptions[id]?.find(t=>t.available)?.transport||'walk';renderMap();renderLocation(true);}
function closeLocation(){selected='';$('location-panel').hidden=true;if(state&&state.status!=='lobby'&&!animating)renderMap();}
function renderLocation(focus=false){
 const location=locations().find(l=>l.id===selected);if(!location){$('location-panel').hidden=true;return;}const content=$('location-content');content.replaceChildren();const header=el('div','venue-header'),picture=el('div','venue-art');picture.innerHTML='<svg xmlns="'+NS+'" viewBox="-58 -84 116 110">'+art().building(location.id)+'</svg>';const title=el('div');title.append(el('h2','',labels[location.id]),el('small','',state.map.zones.find(z=>z.id===location.zone)?.name||''));header.append(picture,title);content.append(header);
 const current=me()?.locationId===selected,closed=!location.openPhases.includes(state.phase);if(closed)content.append(el('p','panel-note','สถานที่นี้ปิดในช่วงวันทำงาน เปิดวันหยุด'));
 if(current){content.append(el('h3','panel-section-title','คุณอยู่ที่นี่ · ทำอะไรดี?'));const actions=state.actions.filter(a=>!['end_phase','play_card','discard_card','buy_food','buy_eat','eat_food','buy_item','cook','study_degree','salvage','apply_job','accept_job'].includes(a.type)&&!(a.type==='bank'&&a.payload.operation==='repay'));for(const a of actions){const b=button('','action-button',()=>action(a.type,a.payload),busy());b.dataset.action=a.type;b.append(el('span','action-icon',symbols[a.type]||'✦'),el('span','',a.label));content.append(b);}window.DowntownLifeUI.render({state,content,location,player:me(),el,button,action,busy:busy(),money,amount,art:art()});if(!actions.length)content.append(el('p','panel-note',myTurn()?'ยังไม่มีกิจกรรมที่ทำได้ ลองใช้การ์ดหรือเดินทาง':'ยังไม่ถึงตาคุณ'));}
 else{content.append(el('h3','panel-section-title','เลือกวิธีเดินทาง'));const options=state.travelOptions[selected]||[];if(!options.length)content.append(el('p','panel-note','ถึงตาคุณแล้วจึงเลือกเดินทางได้'));
 for(const trip of options){const b=button('','transport-row',()=>{selectedTransport=trip.transport;renderMap();perform('game:travel',{locationId:selected,transport:trip.transport});},busy()||!trip.available);b.addEventListener('mouseenter',()=>{selectedTransport=trip.transport;renderMap();});b.addEventListener('focus',()=>{selectedTransport=trip.transport;renderMap();});const copy=el('div');copy.append(el('strong','',transports[trip.transport][1]),el('small','',trip.reason||(trip.transport==='bus'?'เดิน → ป้าย → รถเมล์ → เดิน':amount(trip.distanceTiles*state.map.tileMeters/1000)+' กม.')));const fare=el('div','fare');fare.append(el('strong','',amount(trip.ap)+' AP'),el('small','',trip.fare?money(trip.fare):'ฟรี'));b.append(el('span','transport-icon',transports[trip.transport][0]),copy,fare);content.append(b);}content.append(el('p','route-note','เส้นประบนแผนที่คือเส้นทางของวิธีที่เลือก'));
 }
 $('location-panel').hidden=false;positionPanel(location);if(focus)$('close-location').focus({preventScroll:true});
}
function positionPanel(location){const point=screenPoint(at(location)),panel=$('location-panel'),width=panel.offsetWidth,height=panel.offsetHeight;panel.style.left=Math.max(8,Math.min(innerWidth-width-12,point.x+35))+'px';panel.style.top=Math.max(68,Math.min(innerHeight-height-80,point.y-100))+'px';}
function screenPoint(p){const matrix=$('city-map').getScreenCTM();return matrix?new DOMPoint(p.x,p.y).matrixTransform(matrix):{x:innerWidth/2,y:innerHeight/2};}
function openInfo(content){const heading=content.querySelector('h2');if(heading){heading.id='info-title';$('info-dialog').setAttribute('aria-labelledby','info-title');}$('info-content').replaceChildren(content);if(!$('info-dialog').open)$('info-dialog').showModal();}
function showPlayer(p){
 const content=el('div');content.append(el('h2','',p.name+' · ชีวิตในเมือง'));const education={m3:'ม.3',highschool:'ม.6',vocational:'ปวช.',diploma:'ปวส.',bachelor:'ปริญญาตรี'},career=id=>state.catalog.careers.find(c=>c.id===id)?.name||'ยังไม่มี',list=el('div','detail-list');
 for(const[label,value]of[['เงินสด',money(p.cash)],['หนี้',money(p.debt)],['การศึกษา',education[p.education.level]],['หน่วยกิต',amount(p.education.credits)],['งานหลัก',career(p.mainJobId)],['พาร์ตไทม์',career(p.parttimeJobId)],['ประสบการณ์',p.experience],['รถส่วนตัว',p.ownsCar?'มีแล้ว':'ยังไม่มี']]){const row=el('div');row.append(el('small','',label),el('strong','',value));list.append(row);}content.append(list);
 if(p.id===state.you.id){content.append(el('h3','','การ์ดต่อเนื่องที่ใช้อยู่'));for(const card of state.passives)content.append(el('p','',card.name+' · ต่ออายุ '+money(card.monthlyFee)+'/เดือน'));if(!state.passives.length)content.append(el('p','','ยังไม่มีการ์ดต่อเนื่อง'));}openInfo(content);
}
function showDeck(){const content=el('div'),starter=state.players.find(p=>p.id===state.startingPlayerId);content.append(el('h2','','กองจั่วกลาง'),el('p','','กองนี้ใช้ร่วมกันทุกคน · เหลือ '+state.deck.remaining+'/'+state.deck.size+' ใบ · กองทิ้ง '+state.deck.discardCount+' ใบ'),el('p','','เกมสุ่มผู้เล่นเริ่มก่อน แล้วแจกคนละ 5 ใบตามลำดับ ผู้เล่นจะเติมมือให้ครบ 5 ใบอัตโนมัติเมื่อจบ Weekend ส่วนการสุ่มที่ห้างเป็นการซื้อเพิ่มจากกองเดียวกัน'),el('p','panel-note','ผู้เริ่มเกม: '+(starter?.name||'-')+' · มือสูงสุด 9 ใบ · เมื่อกองหมดจะสับกองทิ้งกลับมา'));openInfo(content);}
function showRoom(){const content=el('div');content.append(el('h2','','ห้อง '+state.roomCode),el('p','',(state.mode==='season'?'Season':'Marathon')+' · เป้าหมาย '+money(state.goal)),button('คัดลอกรหัสห้อง','secondary',copyCode));for(const p of state.players){const row=el('div','info-player');row.append(avatar(p),el('span','',p.name+(p.id===state.you.id?' (คุณ)':'')+(p.connected?'':' · ออฟไลน์')));content.append(row);}const label=el('label','motion-setting'),check=el('input');check.type='checkbox';check.checked=motionOff;check.addEventListener('change',()=>{motionOff=check.checked;localStorage.setItem('downtown-motion-off',motionOff?'1':'0');renderHUD();});label.append(check,el('span','','ลดการเคลื่อนไหว'));content.append(label,el('p','panel-note','เริ่ม Phase ที่อพาร์ตเมนต์ด้วย 24 AP · เลือกกินเองและกลับบ้านนอนอย่างน้อย 4 AP · เติมการ์ดจบ Weekend'));if(state.status==='finished')content.append(button('ดูอันดับ','primary',showResults));openInfo(content);}
async function copyCode(){try{await navigator.clipboard.writeText(state.roomCode);notice('คัดลอกรหัส '+state.roomCode+' แล้ว',true);}catch{notice('รหัสห้อง: '+state.roomCode,true);}}
function endPhase(){if(state.status==='finished')return showResults();if(!myTurn()||busy())return;const p=me();if(p.custody)return action('serve_jail');if(p.sleepAp<4){const content=el('div');content.append(el('h2','','ยังนอนไม่ครบ 4 AP'),el('p','','ถ้าจบช่วงตอนนี้ ช่วงถัดไปจะเสียเวลา 12–18 AP กลับอพาร์ตเมนต์แล้วเลือกนอนก่อน'),button('จบช่วงต่อไป','secondary',()=>action('end_phase')),button('กลับไปนอน','subtle',()=>{$('info-dialog').close();chooseLocation('home');}));openInfo(content);}else action('end_phase');}
function showResults(){if(!state?.scoreboard)return;const content=el('div');content.append(el('h2','','สรุปชีวิตในเมือง'),el('p','','เก็บเงินสุทธิถึงเป้าก่อนชนะ หากครบกำหนดจะเทียบคะแนนทั้งสี่ด้าน'));for(const entry of state.scoreboard){const row=el('div','score-row'),copy=el('div');copy.append(el('strong','',entry.name),el('small','',Object.keys(statLabels).map(k=>statLabels[k]+' '+amount(entry[k])).join(' · ')),el('small','','เงินสุทธิ '+money(entry.netSavings)));row.append(el('b','',entry.rank),copy,el('strong','',amount(entry.total)+' คะแนน'));content.append(row);}content.append(button('Go to lobby','primary',leaveRoom));openInfo(content);}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function animateElement(element,keyframes,options){if(reduced())return Promise.resolve();return element.animate(keyframes,options).finished.catch(()=>{});}
function sceneType(event){if(event.moneyLoss>0)return'money_loss';if(['opening_deal','discard_card'].includes(event.type))return'draw_card';if(event.type==='activity'){if(['market','convenience','restaurant'].includes(event.locationId))return'eat';if(event.locationId==='fitness')return'fitness';if(event.locationId==='hospital')return'heal';return'recreation';}return event.type;}
async function present(event){
 if(event.type==='opening_deal')return animateOpeningDeal(event);if(event.type==='travel'){await animateTravel(event);if(event.entryLoss||event.eventId)await present({...event,type:'travel_outcome',text:event.entryLoss?'ตลาดมืด · สุขภาพ -'+event.entryLoss.health+' / ความสุข -'+event.entryLoss.happiness:event.text});return;}if(event.type==='draw_card'||(event.type==='discard_card'&&!state.deck.pendingDiscard)||event.refillCount>0)await flyCards(event.actorId,event.refillCount||1);
 const scene=$('scene-overlay'),night=['sleep','full_rest','emergency_rest'].includes(event.type);$('game-view').classList.toggle('night',night);scene.className='scene-overlay'+(night?' night':'')+(event.moneyLoss>0?' money-loss':'');$('scene-art').innerHTML=art().actionScene(sceneType(event),{color:state.players.find(p=>p.id===event.actorId)?.color});$('scene-label').textContent=event.text||'ชีวิตในเมือง';$('scene-rewards').replaceChildren();
 for(const[key,value]of Object.entries(event.rewards||{})){if(!value)continue;const chip=el('span','reward-chip'+(value<0?' negative':''),(key==='cash'?'เงิน':key==='ap'?'AP':statLabels[key]||key)+' '+(value>0?'+':'')+amount(value)+(key==='cash'?' ฿':''));chip.style.animationDelay=($('scene-rewards').children.length*.09)+'s';$('scene-rewards').append(chip);}scene.hidden=false;scene.setAttribute('popover','manual');scene.showPopover();await pause(reduced()?100:event.moneyLoss>0?1100:['work','study','study_degree','buy_food','eat_food'].includes(event.type)?280:650);scene.hidePopover();scene.hidden=true;$('game-view').classList.remove('night');
 if(event.phaseNotices?.length)await present({type:'phase_notice',actorId:event.nextPlayerId||event.actorId,text:event.phaseNotices.join(' · ')});
 if(event.moneyLoss>0&&event.type!=='money_loss')await present({type:'money_loss',actorId:event.nextPlayerId||event.actorId,text:'เหตุการณ์เสียเงิน '+money(event.moneyLoss),moneyLoss:event.moneyLoss,rewards:{cash:-event.moneyLoss}});
 if(event.completedPhase){if(event.completedPhase==='weekend')await present({type:'turn_end',actorId:event.actorId,text:'จบตาของ '+event.actorName+' · Turn '+event.completedWeek});if(event.nextPlayerId)await present({type:'turn_start',actorId:event.nextPlayerId,text:(event.completedPhase==='weekend'?'เริ่มตาของ ':'Phase 2/2 · ')+event.nextPlayerName+' · Turn '+event.nextWeek});}
 if(event.applicationResults?.length)for(const result of event.applicationResults){const job=state.catalog.careers.find(j=>j.id===result.jobId),place=locations().find(l=>l.id===job.locationId);await present({type:'apply_job',actorId:event.nextPlayerId||event.actorId,text:result.accepted?'ได้ข้อเสนองานที่ '+place.name+' · '+job.name+' · ประมาณ '+money(job.payByPhase.workday*8)+'/Workday, '+money(job.payByPhase.weekend*8)+'/Weekend (Phase ละ 8 ครั้ง) · '+money(job.payByPhase.workday)+'/AP Workday · อย่าลืมรับงานและไปทำงาน!':'Resume ไม่ผ่าน: '+job.name});}
}
async function flyCards(playerId,count=1){
 if(reduced()||count<1)return;const deck=$('deck-dock').getBoundingClientRect(),start={x:deck.left+deck.width/2,y:deck.top+deck.height/2};let target;
 if(playerId===state.you.id){const hand=document.querySelector('.hand-area').getBoundingClientRect();target={x:hand.left+hand.width*.55,y:hand.top+Math.min(70,hand.height*.5)};}
 else{const token=$('rivals').querySelector('[data-player="'+playerId+'"]')?.getBoundingClientRect();target=token?{x:token.left+token.width/2,y:token.top+token.height/2}:{x:innerWidth/2,y:innerHeight-80};}
 const flights=[];for(let index=0;index<count;index+=1){const card=el('div','flying-card');card.style.left='0px';card.style.top='0px';$('motion-layer').append(card);flights.push(animateElement(card,[{transform:`translate(${start.x-40}px,${start.y-90}px) rotate(-8deg) scale(.55)`,opacity:0},{transform:`translate(${start.x-40}px,${start.y-145}px) rotate(5deg) scale(.82)`,opacity:1,offset:.3},{transform:`translate(${target.x-42+index*4}px,${target.y-58-index*2}px) rotate(${index*3-6}deg) scale(.48)`,opacity:0}],{duration:560,delay:index*90,easing:'ease-in-out',fill:'both'}).finally(()=>card.remove()));}await Promise.all(flights);
}
async function animateOpeningDeal(event){
 const tip=$('map-tip'),handSize=event.startingHandSize||5;for(const playerId of event.order||[]){const player=state.players.find(p=>p.id===playerId);tip.textContent='กำลังแจก '+handSize+' ใบให้ '+(player?.name||'ผู้เล่น');await flyCards(playerId,handSize);}
 const starter=state.players.find(p=>p.id===event.startingPlayerId);tip.textContent=(starter?.name||'ผู้เล่นแรก')+' เริ่ม Turn แรกด้วยการ์ด 5 ใบ';notice((starter?.name||'ผู้เล่นแรก')+' ได้เริ่มก่อนด้วยการ์ด 5 ใบ',true);
}
function vehicle(transport,color){
 if(transport==='moto')return'<g class="vehicle-token"><ellipse cy="5" rx="24" ry="6" fill="#35494b20"/><circle cx="-17" r="7" fill="#635a64"/><circle cx="19" r="7" fill="#635a64"/><path d="M-17 0L-6 -15L10 -4H19L13 -24" fill="none" stroke="#aa93ae" stroke-width="6" stroke-linecap="round"/><path d="M-9 -16L5 -16" stroke="#635a64" stroke-width="4"/><path d="M-5 -18L-2 -33L11 -25" fill="none" stroke="'+color+'" stroke-width="8" stroke-linecap="round"/><circle cx="0" cy="-42" r="8" fill="#edc6a5" stroke="#635a64"/><path d="M-9 -42Q-8 -55 3 -52Q9 -48 8 -42" fill="#a8bbc3" stroke="#635a64"/></g>';
 const fill=transport==='bus'?'#89b2be':transport==='taxi'?'#dfc480':color,bus=transport==='bus';return'<g class="vehicle-token"><ellipse cy="5" rx="'+(bus?32:23)+'" ry="7" fill="#35494b20"/><rect x="'+(bus?-33:-25)+'" y="'+(bus?-32:-23)+'" width="'+(bus?66:50)+'" height="'+(bus?32:23)+'" rx="7" fill="'+fill+'" stroke="#635a64" stroke-width="2"/><rect x="'+(bus?-25:-15)+'" y="'+(bus?-28:-20)+'" width="'+(bus?48:27)+'" height="'+(bus?14:11)+'" rx="3" fill="#d4e3df" stroke="#635a64" stroke-width="1.5"/><circle cx="-17" cy="0" r="5" fill="#635a64"/><circle cx="18" cy="0" r="5" fill="#635a64"/><path d="M0 '+(bus?-28:-20)+'v'+(bus?14:11)+(bus?'M-12 -28v14M12 -28v14':'')+'" stroke="#635a64" stroke-width="1.5"/><circle cx="'+(bus?29:22)+'" cy="-10" r="2" fill="#fff5ce"/>'+(transport==='taxi'?'<rect x="-9" y="-30" width="18" height="7" rx="2" fill="#fff5ce" stroke="#635a64"/><text x="0" y="-25" text-anchor="middle" font-size="5" fill="#635a64">TAXI</text>':'')+'</g>';
}
async function animateTravel(event){
 const canvas=$('city-map'),player=state.players.find(p=>p.id===event.actorId);if(!player)return;const target=canvas.querySelector('[data-player="'+event.actorId+'"]');if(target)target.style.opacity='0';const token=svg('g'),route=svg('polyline',{points:points(event.path||[]),class:'map-route'});canvas.append(route,token);
 try{const legs=(event.legs?.length?event.legs:[{transport:event.transport,path:event.path}]).filter(l=>l.path?.length>1),total=legs.reduce((n,l)=>n+l.path.length-1,0);for(const leg of legs){token.setAttribute('class','travel-token'+(leg.transport==='walk'?' token-walking':''));token.innerHTML=leg.transport==='walk'?art().token(player.color,state.players.indexOf(player)):vehicle(leg.transport,player.color);const duration=reduced()?0:Math.max(180,Math.min(1900,450+total*22)*(leg.path.length-1)/total);await moveAlong(token,leg.path,duration);}notice(player.name+' ถึง'+(labels[event.locationId]||'จุดหมาย')+' · '+amount(-(event.rewards?.ap||0))+' AP'+(event.rewards?.cash?' · '+money(event.rewards.cash):''),true);}finally{token.remove();route.remove();if(target)target.style.opacity='';}
}
function moveAlong(token,path,duration){const positions=path.map(at);if(!positions.length)return Promise.resolve();if(!duration){const p=positions.at(-1);token.setAttribute('transform',`translate(${p.x} ${p.y})`);return Promise.resolve();}return new Promise((resolve,reject)=>{let start;function frame(now){try{start??=now;const progress=Math.max(0,Math.min(1,(now-start)/duration)),scaled=progress*(positions.length-1),index=Math.min(positions.length-2,Math.floor(scaled)),fraction=scaled-index,a=positions[index],b=positions[index+1];token.setAttribute('transform',`translate(${a.x+(b.x-a.x)*fraction} ${a.y+(b.y-a.y)*fraction})`);if(progress<1)requestAnimationFrame(frame);else resolve();}catch(error){reject(error);}}requestAnimationFrame(frame);});}
async function drain(){if(animating)return;animating=true;renderHUD();renderCards();try{while(queue.length&&state)await present(queue.shift());}catch(error){console.error('Presentation error',error);}finally{animating=false;$('scene-overlay').hidden=true;$('game-view').classList.remove('night');if(state&&state.status!=='lobby')renderMap();renderHUD();renderCards();if(selected)renderLocation();if(state?.status==='finished'&&!resultsShown){resultsShown=true;showResults();}}}
function onState(next){if(!next?.you)return;const prior=state,opening=prior?.status==='lobby'&&next.status==='playing'&&next.openingDeal;state=next;saveRoom(next);const event=next.lastPresentation,isNew=event?.id!==lastPresentation;if(event)lastPresentation=event.id;if(opening){setHand(true);queue.push({...next.openingDeal,type:'opening_deal'});if(event)queue.push(event);}else if(prior&&isNew&&event){if(event.actorId===next.you.id&&['draw_card','play_card','discard_card'].includes(event.type)||event.actorId===next.you.id&&event.refillCount>0)setHand(true);queue.push(event);}render();if(queue.length)drain();}
async function enter(event,payload){if(requestPending||!socket.connected)return;const name=$('player-name').value.trim();if(!name){$('player-name').focus();return notice('ใส่ชื่อตัวละครก่อนเข้าเมือง');}requestPending=true;try{const reply=await socket.timeout(7000).emitWithAck(event,{name,...payload});if(!reply.ok)notice(reply.error);else saveRoom(reply);}catch{notice('เชื่อมต่อห้องไม่ได้ กรุณาลองอีกครั้ง');}finally{requestPending=false;render();}}
$('create-form').addEventListener('submit',e=>{e.preventDefault();enter('room:create',{mode:$('game-mode').value,singlePlayer:$('play-mode').value==='solo'});});$('join-form').addEventListener('submit',e=>{e.preventDefault();enter('room:join',{code:$('room-code-input').value.trim().toUpperCase()});});$('start-game').addEventListener('click',()=>perform('game:start',{code:state.roomCode}));$('copy-code').addEventListener('click',copyCode);$('room-menu').addEventListener('click',showRoom);$('details-button').addEventListener('click',()=>showPlayer(me()));$('close-location').addEventListener('click',closeLocation);$('close-info').addEventListener('click',()=>$('info-dialog').close());$('end-phase').addEventListener('click',endPhase);$('hand-toggle').addEventListener('click',()=>setHand(document.querySelector('.hand-area').classList.contains('collapsed')));
$('info-dialog').addEventListener('cancel',e=>e.preventDefault());addEventListener('resize',()=>{if(selected)positionPanel(locations().find(l=>l.id===selected));});
$('exit-room').addEventListener('click',askToLeave);$('deck-dock').addEventListener('click',showDeck);$('working-button').addEventListener('click',()=>{const work=state.actions.find(a=>a.type==='work');if(work)action(work.type,work.payload);else{const job=state.catalog.careers.find(j=>j.id===me().mainJobId||j.id===me().parttimeJobId);if(job)chooseLocation(job.locationId);}});
$('hero-faces').innerHTML=['#d87e72','#86aaa0','#9c93ba','#d9ac67'].map((color,index)=>art().avatar(color,index)).join('');
if(typeof window.io!=='function'){connection('โหลดการเชื่อมต่อไม่ได้',true);notice('เปิดเกมผ่านเซิร์ฟเวอร์ของเดโม');return;}
socket=window.io();socket.on('game:state',onState);socket.on('room:closed',({roomCode})=>{if(state?.roomCode===roomCode)returnToLanding('โฮสต์ยกเลิกห้องแล้ว สร้างหรือเข้าห้องใหม่ได้เลย');});socket.on('connect',async()=>{if(tabReplaced)return;connection('เชื่อมต่อแล้ว');const room=readRoom();if(room){try{const reply=await socket.timeout(7000).emitWithAck('room:resume',{code:room.roomCode,playerId:room.playerId});if(!reply.ok){returnToLanding('ห้องเดิมปิดแล้ว สร้างหรือเข้าห้องใหม่ได้เลย');}}catch{notice('กลับเข้าห้องเดิมไม่ได้ กรุณาลองโหลดใหม่');}}});socket.on('room:replaced',()=>{tabReplaced=true;queue=[];selected='';requestPending=false;state=null;$('info-dialog').close();$('location-panel').hidden=true;socket.disconnect();connection('เกมย้ายไปแท็บอื่น',true);render();notice('ตัวละครนี้เปิดในแท็บอื่นแล้ว เล่นต่อที่แท็บนั้น หรือโหลดหน้านี้ใหม่เพื่อกลับมา');});socket.on('disconnect',()=>{if(tabReplaced)return;connection('กำลังเชื่อมต่อใหม่',true);requestPending=false;notice('การเชื่อมต่อหลุด กำลังกลับเข้าห้องเดิม');});socket.on('connect_error',()=>connection('เชื่อมต่อไม่ได้',true));render();
})();
