/* Server-authoritative play and original SVG illustration. */
(() => {
'use strict';
// R8: Web Audio click SFX
let _audioCtx,_sfxGain,_sfxMuted=false,_sfxVol=0.4;
function _ensureAudio(){if(!_audioCtx){_audioCtx=new(window.AudioContext||window.webkitAudioContext)();_sfxGain=_audioCtx.createGain();_sfxGain.gain.value=_sfxMuted?0:_sfxVol;_sfxGain.connect(_audioCtx.destination);}}
let _lastSfxTime=0;
function playSfxClick(){if(_sfxMuted||_sfxVol===0)return;try{_ensureAudio();if(_audioCtx&&_audioCtx.state==='suspended')_audioCtx.resume();const o=_audioCtx.createOscillator(),g=_audioCtx.createGain();o.connect(g);g.connect(_sfxGain);o.frequency.value=600;o.type='sine';g.gain.setValueAtTime(0.12,_audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(0.001,_audioCtx.currentTime+0.08);o.start();o.stop(_audioCtx.currentTime+0.08);}catch{}}
document.addEventListener('pointerdown', () => { if(_audioCtx&&_audioCtx.state==='suspended')_audioCtx.resume(); }, {once:true});
document.addEventListener('keydown', () => { if(_audioCtx&&_audioCtx.state==='suspended')_audioCtx.resume(); }, {once:true});
document.addEventListener('click', (e) => {
  if (e.target.closest('button:not(:disabled), [role="button"], select, a')) {
    if(Date.now()-_lastSfxTime<50)return;
    _lastSfxTime=Date.now();
    playSfxClick();
  }
}, true);
// R9: BGM
let _bgmAudio=null,_bgmMuted=false,_bgmVol=0.3,_bgmStarted=false;
async function startBgm(){if(_bgmStarted)return;_bgmStarted=true;try{const res=await fetch('/api/bgm');const files=await res.json();if(files&&files.length>0){_bgmAudio=new Audio('/bgm/'+encodeURIComponent(files[0]));_bgmAudio.loop=true;_bgmAudio.volume=_bgmMuted?0:_bgmVol;_bgmAudio.play().catch(()=>{});}}catch(e){}}
document.addEventListener('click',startBgm,{once:true});
document.addEventListener('keydown',startBgm,{once:true});
if(localStorage.getItem('dt-sfx-vol'))_sfxVol=Number(localStorage.getItem('dt-sfx-vol'))/100;
if(localStorage.getItem('dt-sfx-muted'))_sfxMuted=localStorage.getItem('dt-sfx-muted')==='1';
if(localStorage.getItem('dt-bgm-vol'))_bgmVol=Number(localStorage.getItem('dt-bgm-vol'))/100;
if(localStorage.getItem('dt-bgm-muted'))_bgmMuted=localStorage.getItem('dt-bgm-muted')==='1';
const $=id=>document.getElementById(id),NS='http://www.w3.org/2000/svg',tile=30,storageKey='downtown-local-room-v1';
const statLabels={knowledge:'เธเธงเธฒเธกเธฃเธนเน',wealth:'เธเธฒเธฃเน€เธเธดเธ',happiness:'เธเธงเธฒเธกเธชเธธเธ',health:'เธชเธธเธเธ เธฒเธ'};
const transports={walk:['๐ถ','เน€เธ”เธดเธเน€เธ—เนเธฒ'],bus:['๐','เธฃเธ–เน€เธกเธฅเน'],moto:['๐ต','เธงเธดเธเธกเธญเน€เธ•เธญเธฃเนเนเธเธเน'],taxi:['๐•','เนเธ—เนเธเธเธตเน'],car:['๐','เธฃเธ–เธชเนเธงเธเธ•เธฑเธง']};
const labels={black_market:'เธ•เธฅเธฒเธ”เธกเธทเธ”',home:'เธญเธเธฒเธฃเนเธ•เน€เธกเธเธ•เน',condo:'เธเธญเธเนเธ”',school:'เนเธฃเธเน€เธฃเธตเธขเธ',university:'เธกเธซเธฒเธงเธดเธ—เธขเธฒเธฅเธฑเธข',hospital:'เนเธฃเธเธเธขเธฒเธเธฒเธฅ',bank:'เธเธเธฒเธเธฒเธฃ',market:'เธ•เธฅเธฒเธ”เธฃเธดเธกเธเธฅเธญเธ',convenience:'เธฃเนเธฒเธเธชเธฐเธ”เธงเธเธเธทเนเธญ',job_center:'เธชเธณเธเธฑเธเธเธฒเธเธเธฑเธ”เธซเธฒเธเธฒเธ',mall:'เธซเนเธฒเธเธชเธฃเธฃเธเธชเธดเธเธเนเธฒ',restaurant:'เธฃเนเธฒเธเธญเธฒเธซเธฒเธฃ',fitness:'เธเธดเธ•เน€เธเธช',automotive:'เธจเธนเธเธขเนเธขเธฒเธเธขเธเธ•เน',ticket_venue:'เนเธฃเธเธซเธเธฑเธเนเธฅเธฐเธเธดเธเธเธฃเธฃเธก',hangout:'Hang out',casino:'เธเธฒเธชเธดเนเธ',city_exit:'เธญเธญเธเธชเธนเนเธเธเธเธ—'};
const symbols={sleep:'โพ',full_rest:'โพ',emergency_rest:'โ',study:'โ–ค',choose_track:'โ–ค',work:'โ’',apply_job:'โ',activity:'โฆ',casino:'โ ',bank:'เธฟ',form_partnership:'โก',draw_card:'โ–ฐ',buy_car:'๐'};
let socket,state=null,requestPending=false,animating=false,selected='',selectedTransport='walk',lastPresentation='',queue=[],noticeTimer,resultsShown=false,tabReplaced=false;
let motionOff=localStorage.getItem('downtown-motion-off')==='1';
const art=()=>window.DowntownArt;
const el=(tag,cls='',value)=>{const n=document.createElement(tag);n.className=cls;if(value!==undefined)n.textContent=String(value);return n;};
const svg=(tag,attrs={})=>{const n=document.createElementNS(NS,tag);for(const[k,v]of Object.entries(attrs))n.setAttribute(k,String(v));return n;};
const svgt=(parent,x,y,value,attrs={})=>{const n=svg('text',{x,y,...attrs});n.textContent=value;parent.append(n);return n;};
const amount=value=>new Intl.NumberFormat('th-TH',{maximumFractionDigits:2}).format(Number(value)||0),money=value=>amount(value)+' เธฟ';
const me=()=>state?.players.find(p=>p.id===state.you.id),active=()=>state?.players.find(p=>p.id===state.activePlayerId);
const myTurn=()=>state?.status==='playing'&&state.you.id===state.activePlayerId,busy=()=>requestPending||animating,locations=()=>state?.map?.locations||[];
const at=p=>({x:(p.x+.5)*tile,y:(p.y+.5)*tile}),points=path=>path.map(p=>{const c=at(p);return c.x+','+c.y;}).join(' ');
const reduced=()=>motionOff||matchMedia('(prefers-reduced-motion: reduce)').matches;
const avatar=p=>{const h=el('span');h.innerHTML=art().avatar(p.color,state.players.indexOf(p));return h.firstElementChild;};
function button(text,cls,fn,disabled=false){const b=el('button',cls,text);b.type='button';b.disabled=disabled;b.addEventListener('click',e=>{if(b.dataset.action==='study_degree'||/เน€เธฃเธตเธขเธ|Study/.test(b.textContent))activityBurst(b,'๐“');else if(/Working|^Work/.test(b.textContent))activityBurst(b,'โ’');fn(e);});return b;}
function activityBurst(button,icon){if(reduced())return;const rect=button.getBoundingClientRect(),host=button.closest('dialog')||document.body;for(let i=0;i<7;i++){const particle=el('span','activity-particle',icon==='โ’'?['โ’','๐“','๐ช'][i%3]:icon);particle.setAttribute('aria-hidden','true');particle.style.left=(rect.left+rect.width/2)+'px';particle.style.top=(rect.top+rect.height/2)+'px';host.append(particle);animateElement(particle,[{transform:'translate(-50%,-50%) scale(.5)',opacity:1},{transform:`translate(${(i-3)*32}px,${-55-Math.sin(i)*30}px) rotate(${(i-3)*24}deg) scale(1.2)`,opacity:0}],{duration:650,easing:'ease-out'}).finally(()=>particle.remove());}}
function notice(message,success=false,actingPlayer=false){clearTimeout(noticeTimer);$('notice').textContent=message;$('notice').className='notice'+(success?' success':'');$('notice').hidden=false;$('notice').dataset.actingPlayer=actingPlayer?'1':'';if(!actingPlayer){noticeTimer=setTimeout(()=>{$('notice').hidden=true;},5000);}}
function dismissAllNotices(){clearTimeout(noticeTimer);if(!$('notice').hidden){$('notice').hidden=true;}}
document.addEventListener('click',()=>{if($('notice').dataset.actingPlayer==='1'&&!$('notice').hidden)dismissAllNotices();});
function readRoom(){try{return JSON.parse(localStorage.getItem(storageKey)||'null');}catch{return null;}}
function saveRoom(room){localStorage.setItem(storageKey,JSON.stringify({roomCode:room.roomCode,playerId:room.playerId||room.you?.id}));}
function returnToLanding(message){
 const player=me();if(player)$('player-name').value=player.name;
 localStorage.removeItem(storageKey);state=null;queue=[];lastPresentation='';resultsShown=false;selected='';requestPending=false;
 $('info-dialog').close();$('location-panel').hidden=true;$('scene-overlay').hidden=true;$('game-view').classList.remove('night');setHand(false);render();
 $('player-name').focus({preventScroll:true});if(message)notice(message,true);
}
async function leaveRoom(){
 if(!state||!['lobby','finished'].includes(state.status)||busy()||!socket?.connected)return;
 const host=state.you.host;requestPending=true;$('info-dialog').close();renderLobby();
 try{const reply=await socket.timeout(7000).emitWithAck('room:leave',{});if(!reply.ok)notice(reply.error);else if(state)returnToLanding(host&&state.status==='lobby'?'เธขเธเน€เธฅเธดเธเธซเนเธญเธเนเธฅเนเธง เธชเธฃเนเธฒเธเธซเนเธญเธเนเธซเธกเนเนเธ”เนเน€เธฅเธข':'เธญเธญเธเธเธฒเธเธซเนเธญเธเนเธฅเนเธง');}
 catch{notice('เธญเธญเธเธเธฒเธเธซเนเธญเธเนเธกเนเนเธ”เน เธเธฃเธธเธ“เธฒเธฅเธญเธเธญเธตเธเธเธฃเธฑเนเธเน€เธกเธทเนเธญเน€เธเธทเนเธญเธกเธ•เนเธญเนเธฅเนเธง');}
 finally{requestPending=false;render();}
}
function askToLeave(){
 if(!state||state.status!=='lobby'||busy())return;
 if(!state.you.host||state.players.length===1)return leaveRoom();
 const content=el('div');content.append(el('h2','','เธขเธเน€เธฅเธดเธเธซเนเธญเธเธเธตเน?'),el('p','','เน€เธเธทเนเธญเธเนเธเธซเนเธญเธเธเธฐเธเธฅเธฑเธเนเธเธซเธเนเธฒเน€เธฃเธดเนเธกเธ•เนเธเธเธฃเนเธญเธกเธเธฑเธ เนเธฅเธฐเธฃเธซเธฑเธชเธซเนเธญเธเธเธตเนเธเธฐเนเธเนเนเธกเนเนเธ”เน'),button('Exit ยท เธขเธเน€เธฅเธดเธเธซเนเธญเธ','exit-button',leaveRoom),button('เธเธฅเธฑเธเนเธเธซเนเธญเธ','subtle',()=>$('info-dialog').close()));openInfo(content);
}
function connection(text,offline=false){$('connection-status').textContent=text;$('connection-status').className='connection-status'+(offline?' offline':'');}
function action(type,payload={}){return perform('game:action',{type,payload});}
async function perform(event,payload){
 if(busy()||!socket?.connected)return;if(event==='game:action'||event==='game:travel')payload={...payload,expectedVersion:state.version};requestPending=true;for(const b of $('info-content').querySelectorAll('button'))b.disabled=true;renderHUD();renderCards();if(selected)renderLocation();
 try{const ack=await socket.timeout(7000).emitWithAck(event,payload);if(!ack?.ok)notice(translateError(ack?.error||'เธ—เธณเธฃเธฒเธขเธเธฒเธฃเนเธกเนเนเธ”เน'));}
 catch{notice('เธขเธฑเธเนเธกเนเนเธ”เนเธฃเธฑเธเธเธณเธ•เธญเธเธเธฒเธเน€เธกเธทเธญเธ เธเธฃเธธเธ“เธฒเธฃเธญเธชเธฑเธเธเธฃเธนเนเนเธฅเนเธงเธฅเธญเธเนเธซเธกเน');}
 finally{requestPending=false;renderHUD();renderCards();if(selected)renderLocation();if($('info-dialog').open){const status=el('p','panel-note','เธญเธฑเธเน€เธ”เธ•เนเธฅเนเธง ยท เธเธดเธ”เธซเธเนเธฒเธ•เนเธฒเธเธ”เนเธงเธขเธเธธเนเธก ร— เน€เธกเธทเนเธญเธเธฃเนเธญเธก');$('info-content').append(status);}}
}
function translateError(text){return({'It is not your turn':'เธขเธฑเธเนเธกเนเธ–เธถเธเธ•เธฒเธเธธเธ“','Action is unavailable now':'เธเธดเธเธเธฃเธฃเธกเธเธตเนเธขเธฑเธเธ—เธณเนเธกเนเนเธ”เน เธฅเธญเธเน€เธฅเธทเธญเธเนเธซเธกเน','Already at destination':'เธเธธเธ“เธญเธขเธนเนเธ—เธตเนเธเธตเนเนเธฅเนเธง','A car is required':'เธ•เนเธญเธเธกเธตเธฃเธ–เธชเนเธงเธเธ•เธฑเธงเธเนเธญเธ','Finish choosing cards to discard first':'เน€เธฅเธทเธญเธเธเธฒเธฃเนเธ”เธ—เธตเนเธเธฐเธ—เธดเนเธเนเธซเนเธเธฃเธเธเนเธญเธ'})[text]||text;}
function render(){
 $('landing-view').hidden=!!state;$('waiting-view').hidden=!state||state.status!=='lobby';$('game-view').hidden=!state||state.status==='lobby';$('room-menu').hidden=!state;
 if(!state)return;if(state.status==='lobby')renderLobby();else{renderHUD();if(!animating)renderMap();renderCards();if(selected)renderLocation();if(state.status==='finished'&&!resultsShown&&!animating&&!queue.length){resultsShown=true;setTimeout(showResults,100);}}
}
function renderLobby(){
 $('waiting-code').textContent=state.roomCode;$('waiting-art').innerHTML=art().actionScene('apply_job');$('waiting-players').replaceChildren();
 for(const p of state.players){const cell=el('div','waiting-player');cell.append(avatar(p),el('strong','',p.name),el('small','',p.id===state.you.id?'เธเธธเธ“':'เธเธฒเธงเน€เธกเธทเธญเธ'));$('waiting-players').append(cell);}
 $('start-game').hidden=!state.you.host;$('start-game').disabled=busy()||!state.singlePlayer&&state.players.length<2;$('waiting-message').textContent=state.you.host?(state.singlePlayer?'Single player ยท เน€เธฃเธดเนเธกเนเธ”เนเน€เธฅเธข':'เนเธเธฃเนเธฃเธซเธฑเธชเธซเนเธญเธเนเธซเนเน€เธเธทเนเธญเธ เนเธฅเนเธงเน€เธฃเธดเนเธกเน€เธกเธทเนเธญเธเธฃเนเธญเธก'):'เธฃเธญเนเธฎเธชเธ•เนเน€เธฃเธดเนเธกเน€เธเธก';
 $('exit-room').textContent=state.you.host?'Exit ยท เธขเธเน€เธฅเธดเธเธซเนเธญเธ':'Exit ยท เธญเธญเธเธเธฒเธเธซเนเธญเธ';$('exit-room').disabled=busy()||!socket?.connected;
}
function renderHUD(){
 if(!state||state.status==='lobby')return;const p=me();if(!p)return;
 const sum=$('self-summary');sum.replaceChildren();const heading=el('div','self-heading'),text=el('div');text.append(el('strong','',p.name),el('small','',myTurn()?'เธ–เธถเธเธ•เธฒเธเธญเธเธเธธเธ“':'เธเธฒเธงเน€เธกเธทเธญเธเธเธญเธเธเธธเธ“'));heading.append(avatar(p),text);sum.append(heading,el('div','cash-row',money(p.cash)),el('div','net-row','เธชเธธเธ—เธเธด '+money(p.netSavings)+' / '+money(state.goal)));
 const ap=el('div','ap-row');ap.append(el('small','','เน€เธงเธฅเธฒเธ—เธตเนเน€เธซเธฅเธทเธญ'),el('strong','',amount(p.ap)+' AP'));sum.append(ap);
 sum.append(el('div','sleep-pill'+(p.sleepAp<4?' warning':''),(p.sleepAp>=4?'โพ เธเธญเธเธเธฃเธเนเธฅเนเธง':'โพ เธเธญเธ '+amount(p.sleepAp)+'/4 AP')+(p.hasEaten?' ยท เธเธดเธเธเนเธฒเธงเนเธฅเนเธง':' ยท เธขเธฑเธเนเธกเนเธเธดเธ')));
 if(p.phaseNotices?.length)sum.append(el('small','phase-notices',p.phaseNotices.join(' ยท ')));
 const bars=$('stats-bars');if(!bars.children.length)for(const[key,label]of Object.entries(statLabels)){const row=el('div','stat-row');row.dataset.stat=key;const top=el('div','stat-top');top.append(el('span','',label),el('b'));const track=el('div','stat-track');track.append(el('div','stat-fill'));row.append(top,track);bars.append(row);}
 for(const row of bars.children){const value=p.stats[row.dataset.stat];row.querySelector('b').textContent=amount(value);row.querySelector('.stat-fill').style.width=Math.max(0,Math.min(100,value))+'%';}
 const a=active()||p;$('turn-avatar').replaceChildren(avatar(a));const turn=state.week;
 $('turn-label').textContent=state.status==='finished'?'เธเธเน€เธฃเธทเนเธญเธเธฃเธฒเธงเนเธเน€เธกเธทเธญเธ':'Turn '+turn;
 $('phase-label').textContent='Phase '+(state.phase==='workday'?1:2)+'/2';$('active-name').textContent=a.name+(myTurn()?' (เธเธธเธ“)':'')+(p.custody?' ยท เธเธงเธเธเธธเธกเธ•เธฑเธง':''); let timerLabel = $('timer-label'); if (!timerLabel) { timerLabel = el('small', 'timer-label'); timerLabel.id = 'timer-label'; $('active-name').after(timerLabel); }
 $('end-phase').disabled=!myTurn()||busy()||!!state.deck?.pendingDiscard;$('end-phase').textContent=state.status==='finished'?'เธ”เธนเธญเธฑเธเธ”เธฑเธ':'เธเธเธเนเธงเธ โ’';if(state.status==='finished')$('end-phase').disabled=false;
 $('deck-count').textContent=state.deck.remaining+'/'+state.deck.size;
 const jobs=[p.mainJobId,p.parttimeJobId].filter(Boolean).map(id=>state.catalog.careers.find(j=>j.id===id));$('working-button').hidden=!jobs.length;$('working-button').disabled=!myTurn()||busy()||p.custody;$('working-button').title=jobs.map(j=>j.name).join(' / ');
 const refillTarget=state.deck?.refillToHandSize??5;const handLeft=refillTarget-state.hand.length;
 $('map-tip').textContent=state.deck?.pendingDiscard?'เน€เธฅเธทเธญเธเธเธฒเธฃเนเธ”เนเธเธกเธทเธญเน€เธเธทเนเธญเธ—เธดเนเธเธญเธตเธ '+state.deck.pendingDiscard.count+' เนเธ':!myTurn()?'เธฃเธญ '+a.name+' ยท เน€เธฅเธทเธญเธเธญเธฒเธเธฒเธฃเน€เธเธทเนเธญเธ”เธนเธชเธ–เธฒเธเธ—เธตเนเนเธ”เน':state.phase==='weekend'&&handLeft>0?'เธเธ Weekend โ’ เธเธฑเนเธงเน€เธ•เธดเธกเธกเธทเธญเธญเธตเธ '+handLeft+' เนเธ ยท เน€เธฅเธทเธญเธเธญเธฒเธเธฒเธฃเน€เธเธทเนเธญเน€เธฅเนเธ':'เน€เธฅเธทเธญเธเธญเธฒเธเธฒเธฃเน€เธเธทเนเธญเน€เธฅเนเธเธซเธฃเธทเธญเธเธ Phase';
 $('seasonal-banner').hidden=!state.seasonal;if(state.seasonal)$('seasonal-banner').textContent='โฆ '+state.seasonal.name+' ยท '+state.seasonal.remaining+' เธชเธฑเธเธ”เธฒเธซเน';
 $('rivals').replaceChildren();for(const other of state.players){const b=button('','rival'+(other.id===state.activePlayerId?' active':''),()=>showPlayer(other));b.dataset.player=other.id;b.title=other.name+(other.connected?'':' ยท เธญเธญเธเนเธฅเธเน');b.setAttribute('aria-label','เธ”เธนเธชเธ–เธฒเธเธฐ '+other.name);b.append(avatar(other));const dot=el('i','rival-dot');if(!other.connected)dot.style.background='#aaa';b.append(dot);$('rivals').append(b);}document.body.classList.toggle('reduce-motion',motionOff);
}
function cardTheme(card){if(card.effect?.drawCount)return['#c4d8bd','โป','เนเธฅเธเธเธฒเธฃเนเธ”'];if(card.kind==='passive')return['#c8d9d2','โก','เธ•เนเธญเน€เธเธทเนเธญเธ'];if(card.effect?.cash||card.effect?.monthlyIncome||card.effect?.weeklyIncome)return['#ebcf93','เธฟ','เนเธญเธเธฒเธช'];if(card.effect?.experience)return['#bbd3dc','โ’','เธเธฃเธฐเธชเธเธเธฒเธฃเธ“เน'];if(card.effect?.knowledge)return['#bbd3dc','โ–ค','เธ—เธฑเธเธฉเธฐ'];if(card.effect?.carOwnership||card.effect?.travelDiscount)return['#c8c2db','โ','เน€เธ”เธดเธเธ—เธฒเธ'];return['#e9c1ad','โฆ','เธเธตเธงเธดเธ•'];}
function renderCards(){
 if(!state||state.status==='lobby')return;$('hand-count').textContent=state.hand.length;const phint=state.deck.pendingDiscard?'เน€เธฅเธทเธญเธเธ—เธดเนเธ '+state.deck.pendingDiscard.count+' เนเธ':state.hand.length>0?'เน€เธฅเธทเธญเธเธเธฒเธฃเนเธ”เน€เธเธทเนเธญเธ”เธนเนเธฅเธฐเนเธเน':'เธกเธทเธญเธงเนเธฒเธ ยท เธเธญเธเธเธฑเนเธงเธเธฐเน€เธ•เธดเธกเธกเธทเธญเนเธซเนเธเธฃเธ '+(state.deck?.refillToHandSize??5)+' เนเธเน€เธกเธทเนเธญเธเธ Weekend';$('hand-hint').textContent=phint;$('hand-list').replaceChildren();
 state.hand.forEach((card,index)=>{const[color,symbol,kind]=cardTheme(card),b=button('','hand-card',()=>showCard(index),busy());b.dataset.cardIndex=index;b.style.setProperty('--card-color',color);b.style.setProperty('--tilt',((index-(state.hand.length-1)/2)*3)+'deg');b.style.setProperty('--lift',(Math.abs(index-(state.hand.length-1)/2)*2)+'px');b.title=card.name;b.setAttribute('aria-label',(state.deck.pendingDiscard?'เน€เธฅเธทเธญเธเธ—เธดเนเธ ':'เธ”เธนเธเธฒเธฃเนเธ” ')+card.name);const picture=el('div','card-picture');picture.innerHTML=art().actionScene(card.effect?.experience?'work':card.effect?.knowledge?'study':card.effect?.drawCount?'draw_card':card.effect?.cash?'work':card.effect?.carOwnership?'buy_car':'play_card');b.append(picture,el('span','card-kind',kind+(card.kind==='passive'?' ยท PASSIVE':' ยท ACTIVE')),el('strong','',card.name),el('small','','1 AP ยท '+money(card.cost)));$('hand-list').append(b);});
 if(!state.hand.length)$('hand-list').append(el('small','','เธกเธทเธญเธงเนเธฒเธ ยท เธเธญเธเธเธฑเนเธงเธเธฐเน€เธ•เธดเธกเธกเธทเธญเธเธฃเธ '+(state.deck?.refillToHandSize??5)+' เนเธเน€เธกเธทเนเธญเธเธ Weekend เธเธญเธเธเธธเธ“'));
}
function showCard(index){
 const card=state.hand[index];if(!card)return;const[color,symbol,kind]=cardTheme(card),content=el('div');content.append(el('span','eyebrow',kind+' ยท '+card.kind.toUpperCase()),el('h2','',card.name));const picture=el('div','card-detail-art');picture.style.setProperty('--card-color',color);picture.innerHTML=art().actionScene(card.effect?.experience?'work':card.effect?.knowledge?'study':card.effect?.drawCount?'draw_card':card.effect?.cash?'work':'play_card');content.append(picture,el('p','',card.description));
 for(const[key,value]of Object.entries(card.effect||{})){const names={...statLabels,cash:'เน€เธเธดเธ',ap:'AP',weeklyIncome:'เธเธฑเธเธเธฅ/Turn',experience:'เธเธฃเธฐเธชเธเธเธฒเธฃเธ“เน',monthlyIncome:'เธฃเธฒเธขเนเธ”เน/เน€เธ”เธทเธญเธ',travelDiscount:'เธชเนเธงเธเธฅเธ”เน€เธ”เธดเธเธ—เธฒเธ',eventShield:'เธเธฑเธเน€เธซเธ•เธธเธเธฒเธฃเธ“เน',carOwnership:'เธฃเธ–เธชเนเธงเธเธ•เธฑเธง',partnerToken:'เธซเธธเนเธเธชเนเธงเธ',drawCount:'เธเธฑเนเธง',discardCount:'เธ—เธดเนเธ'};content.append(el('span','card-effect',(names[key]||key)+' '+(typeof value==='number'&&value>0?'+':'')+amount(value)));}
 content.append(el('p','card-cost','เนเธเน 1 AP'+(card.cost?' ยท '+money(card.cost):'')+(card.monthlyFee?' ยท เธ•เนเธญเธญเธฒเธขเธธ '+money(card.monthlyFee)+'/เน€เธ”เธทเธญเธ':'')));if(card.playAt)content.append(el('p','panel-note','เนเธเนเนเธ”เนเธ—เธตเน '+labels[card.playAt]));
 if(card.noUseButton&&!state.deck.pendingDiscard){content.append(el('p','panel-note','เธเธฒเธฃเนเธ”เธเธตเนเนเธเนเธเธฒเธเธเนเธฒเธเธ•เธฅเธฒเธ”เธซเธฅเธฑเธเธ—เธฃเธฑเธเธขเนเน€เธเธตเธขเธเน€เธ—เนเธฒเธเธฑเนเธ (เธเธทเนเธญเนเธเธเธซเธธเนเธเธชเนเธงเธ)'));openInfo(content);return;}
 const type=state.deck.pendingDiscard?'discard_card':'play_card',allowed=state.actions.find(a=>a.type===type&&a.payload.index===index);content.append(button(state.deck.pendingDiscard?'เธ—เธดเนเธเนเธเธเธตเน โ’':'เนเธเนเธเธฒเธฃเนเธ” โ’','primary',()=>{action(type,allowed.payload);$('info-dialog').close();},!allowed||busy()));if(!allowed)content.append(el('p','panel-note',myTurn()?'เธขเธฑเธเนเธเนเนเธกเนเนเธ”เน: เธ•เธฃเธงเธ AP เน€เธเธดเธ เธชเธ–เธฒเธเธ—เธตเน เธซเธฃเธทเธญเธเธณเธเธงเธเธเธฒเธฃเนเธ”เนเธเธกเธทเธญ':'เน€เธเนเธเนเธเธเนเธงเนเธเนเธญเธ เธขเธฑเธเนเธกเนเธ–เธถเธเธ•เธฒเธเธธเธ“'));openInfo(content);
}
function pathLine(parent,path,attrs={}){if(path?.length)parent.append(svg('polyline',{points:points(path),fill:'none',...attrs}));}
function renderMap(){
 const canvas=$('city-map'),map=state.map;canvas.replaceChildren();canvas.setAttribute('viewBox',`-45 -70 ${map.width*tile+90} ${map.height*tile+110}`);canvas.setAttribute('preserveAspectRatio','xMidYMid meet');const deco=map.decorative||{},base=svg('g');
 // Soft park patches and canals, without a visible tile grid.
 for(const park of deco.parks||[]){const c=at(park);base.append(svg('rect',{x:c.x-15,y:c.y-15,width:park.width*tile,height:park.height*tile,rx:45,fill:'#d0ddb8',opacity:.65}));}
 const river=deco.river;if(river?.points){pathLine(base,river.points,{class:'map-road',stroke:'#b4c9b4','stroke-width':river.width*tile+10});pathLine(base,river.points,{class:'map-road',stroke:'#aad5d0','stroke-width':river.width*tile});pathLine(base,river.points,{class:'map-road',stroke:'#d3e8db','stroke-width':2,'stroke-dasharray':'15 30'});}
 for(const plaza of deco.plazas||[]){const c=at(plaza);base.append(svg('ellipse',{cx:c.x,cy:c.y,rx:plaza.radius*tile,ry:plaza.radius*tile*.7,fill:'#dbcdb0',stroke:'#c1b59e','stroke-width':3}));}canvas.append(base);
 const scenery=svg('g');const occupied=(x,y)=>locations().some(l=>Math.hypot(l.x-x,l.y-y)<2.5)||map.roads.some(r=>(r[0]===r[2]&&Math.abs(x-r[0])<1&&y>=Math.min(r[1],r[3])&&y<=Math.max(r[1],r[3]))||(r[1]===r[3]&&Math.abs(y-r[1])<1&&x>=Math.min(r[0],r[2])&&x<=Math.max(r[0],r[2])));
 for(let i=0;i<88;i++){const x=1+((i*17+3)%37),y=1+((i*11+5)%26);if(occupied(x,y))continue;const c=at({x,y}),g=svg('g',{transform:`translate(${c.x} ${c.y})`,opacity:.75});
 if(i%3===0)g.innerHTML='<path d="M0 0v-18" stroke="#8c9277" stroke-width="3"/><ellipse cy="-20" rx="12" ry="16" fill="#aabd8f" stroke="#91aa83" stroke-width="1.5"/><ellipse cx="-6" cy="-14" rx="8" ry="10" fill="#b9c995"/>';
 else g.innerHTML='<rect x="-17" y="-23" width="34" height="25" rx="3" fill="'+['#e8d9bc','#ddcfc1','#d9dcc7'][i%3]+'" stroke="#b7b5a1" stroke-width="1.5"/><path d="M-20 -23L-9 -33H12L20 -23Z" fill="'+['#c89885','#c5ae91','#bda5a0'][i%3]+'" stroke="#b1a08c"/><rect x="-10" y="-17" width="7" height="9" rx="1" fill="#b6cccc"/><rect x="5" y="-17" width="7" height="9" rx="1" fill="#b6cccc"/>';scenery.append(g);}canvas.append(scenery);
 const roads=svg('g');for(const r of map.roads){const a=at({x:r[0],y:r[1]}),b=at({x:r[2],y:r[3]}),d=`M${a.x} ${a.y}L${b.x} ${b.y}`;roads.append(svg('path',{d,class:'map-road',stroke:'#a8a99a','stroke-width':22}),svg('path',{d,class:'map-road',stroke:'#bdc0af','stroke-width':17}),svg('path',{d,class:'map-road',stroke:'#ece7cf','stroke-width':1.5,'stroke-dasharray':'7 14'}));}canvas.append(roads);
 for(const landmark of deco.landmarks||[]){const c=at(landmark);if(landmark.kind==='temple'){const g=svg('g',{transform:`translate(${c.x} ${c.y})`});g.innerHTML='<rect x="-22" y="-30" width="44" height="30" rx="3" fill="#ede0b9" stroke="#c4b18b"/><path d="M-27 -30L0 -60L27 -30ZM-18 -45L0 -67L18 -45" fill="#d6b07c" stroke="#bda076" stroke-width="2"/><rect x="-5" y="-22" width="10" height="22" fill="#c0a783"/>';canvas.append(g);}else svgt(canvas,c.x,c.y,landmark.name||'',{'font-size':10,fill:'#88a197','text-anchor':'middle'});}
 const zoneAnchors=[{x:7,y:1},{x:27,y:0},{x:3,y:19},{x:30,y:10},{x:9,y:27},{x:28,y:26}];map.zones.forEach((zone,i)=>{const c=at(zoneAnchors[i]);svgt(canvas,c.x,c.y,zone.name,{'font-size':13,fill:'#99a082','text-anchor':'middle','font-weight':600});});
 const route=state.travelOptions?.[selected]?.find(t=>t.transport===selectedTransport);if(route)pathLine(canvas,route.path,{class:'map-route'});
 for(const stop of map.busStops||[]){const c=at(stop),g=svg('g',{transform:`translate(${c.x+15} ${c.y+12})`});g.append(svg('rect',{x:-5,y:-8,width:10,height:11,rx:3,fill:'#91b8be',stroke:'#758f94','stroke-width':1.5}));svgt(g,0,0,'B',{'text-anchor':'middle','font-size':7,fill:'#fffaf0'});canvas.append(g);}
 for(const location of locations()){const c=at(location),closed=!location.openPhases.includes(state.phase),g=svg('g',{class:'map-location'+(selected===location.id?' selected':'')+(closed?' closed':''),transform:`translate(${c.x} ${c.y})`,tabindex:0,role:'button','aria-label':'เน€เธฅเธทเธญเธ '+labels[location.id],'data-location':location.id});g.append(svg('ellipse',{cx:0,cy:-1,rx:55,ry:19,class:'location-ring'}));const building=svg('g',{class:'building-art'});building.innerHTML=art().building(location.id);g.append(building);svgt(g,0,22,labels[location.id],{'text-anchor':'middle',class:'location-label'});const title=svg('title');title.textContent=location.name+(closed?' ยท เธเธดเธ”เธเนเธงเธเธเธตเน':'');g.append(title);g.addEventListener('click',()=>chooseLocation(location.id));g.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();chooseLocation(location.id);}});canvas.append(g);}
 const occupants=new Map();for(const p of state.players.filter(p=>p.id===state.activePlayerId)){const c=at(p.position),key=p.position.x+','+p.position.y,n=occupants.get(key)||0;occupants.set(key,n+1);const g=svg('g',{class:'player-token','data-player':p.id,transform:`translate(${c.x+n*18-8} ${c.y+4})`});g.append(svg('ellipse',{cx:0,cy:0,rx:17,ry:8,class:'token-halo',stroke:p.color,opacity:.9}));const body=svg('g');body.innerHTML=art().token(p.color,state.players.indexOf(p));g.append(body);svgt(g,0,15,p.name,{'text-anchor':'middle',class:'token-name'});canvas.append(g);}
}
function setHand(expanded){document.querySelector('.hand-area').classList.toggle('collapsed',!expanded);$('hand-toggle').setAttribute('aria-expanded',String(expanded));}
function chooseLocation(id){if(animating)return;setHand(false);selected=id;selectedTransport=state.travelOptions[id]?.find(t=>t.available)?.transport||'walk';renderMap();renderLocation(true);}
function closeLocation(){selected='';$('location-panel').hidden=true;if(state&&state.status!=='lobby'&&!animating)renderMap();}
function renderLocation(focus=false){
 const location=locations().find(l=>l.id===selected);if(!location){$('location-panel').hidden=true;return;}const content=$('location-content');content.replaceChildren();const header=el('div','venue-header'),picture=el('div','venue-art');picture.innerHTML='<svg xmlns="'+NS+'" viewBox="-58 -84 116 110">'+art().building(location.id)+'</svg>';const title=el('div');title.append(el('h2','',labels[location.id]),el('small','',state.map.zones.find(z=>z.id===location.zone)?.name||''));header.append(picture,title);content.append(header);
 const current=me()?.locationId===selected,closed=!location.openPhases.includes(state.phase);if(closed)content.append(el('p','panel-note','เธชเธ–เธฒเธเธ—เธตเนเธเธตเนเธเธดเธ”เนเธเธเนเธงเธเธงเธฑเธเธ—เธณเธเธฒเธ เน€เธเธดเธ”เธงเธฑเธเธซเธขเธธเธ”'));
 if(current){content.append(el('h3','panel-section-title','เธเธธเธ“เธญเธขเธนเนเธ—เธตเนเธเธตเน ยท เธ—เธณเธญเธฐเนเธฃเธ”เธต?'));const actions=state.actions.filter(a=>!['end_phase','play_card','discard_card','buy_food','buy_eat','eat_food','buy_item','cook','study_degree','salvage','apply_job','accept_job'].includes(a.type)&&!(a.type==='bank'&&a.payload.operation==='repay'));for(const a of actions){const b=button('','action-button',()=>action(a.type,a.payload),busy());b.dataset.action=a.type;b.append(el('span','action-icon',symbols[a.type]||'โฆ'),el('span','',a.label));content.append(b);}window.DowntownLifeUI.render({state,content,location,player:me(),el,button,action,busy:busy(),money,amount,art:art()});if(!actions.length)content.append(el('p','panel-note',myTurn()?'เธขเธฑเธเนเธกเนเธกเธตเธเธดเธเธเธฃเธฃเธกเธ—เธตเนเธ—เธณเนเธ”เน เธฅเธญเธเนเธเนเธเธฒเธฃเนเธ”เธซเธฃเธทเธญเน€เธ”เธดเธเธ—เธฒเธ':'เธขเธฑเธเนเธกเนเธ–เธถเธเธ•เธฒเธเธธเธ“'));}
 else{content.append(el('h3','panel-section-title','เน€เธฅเธทเธญเธเธงเธดเธเธตเน€เธ”เธดเธเธ—เธฒเธ'));const options=state.travelOptions[selected]||[];if(!options.length)content.append(el('p','panel-note','เธ–เธถเธเธ•เธฒเธเธธเธ“เนเธฅเนเธงเธเธถเธเน€เธฅเธทเธญเธเน€เธ”เธดเธเธ—เธฒเธเนเธ”เน'));
 for(const trip of options){const b=button('','transport-row',()=>{selectedTransport=trip.transport;renderMap();perform('game:travel',{locationId:selected,transport:trip.transport});},busy()||!trip.available);b.addEventListener('mouseenter',()=>{selectedTransport=trip.transport;renderMap();});b.addEventListener('focus',()=>{selectedTransport=trip.transport;renderMap();});const copy=el('div');copy.append(el('strong','',transports[trip.transport][1]),el('small','',trip.reason||(trip.transport==='bus'?'เน€เธ”เธดเธ โ’ เธเนเธฒเธข โ’ เธฃเธ–เน€เธกเธฅเน โ’ เน€เธ”เธดเธ':amount(trip.distanceTiles*state.map.tileMeters/1000)+' เธเธก.')));const fare=el('div','fare');fare.append(el('strong','',amount(trip.ap)+' AP'),el('small','',trip.fare?money(trip.fare):'เธเธฃเธต'));b.append(el('span','transport-icon',transports[trip.transport][0]),copy,fare);content.append(b);}content.append(el('p','route-note','เน€เธชเนเธเธเธฃเธฐเธเธเนเธเธเธ—เธตเนเธเธทเธญเน€เธชเนเธเธ—เธฒเธเธเธญเธเธงเธดเธเธตเธ—เธตเนเน€เธฅเธทเธญเธ'));
 }
 $('location-panel').hidden=false;positionPanel(location);if(focus)$('close-location').focus({preventScroll:true});
}
function positionPanel(location){const point=screenPoint(at(location)),panel=$('location-panel'),width=panel.offsetWidth,height=panel.offsetHeight;panel.style.left=Math.max(8,Math.min(innerWidth-width-12,point.x+35))+'px';panel.style.top=Math.max(68,Math.min(innerHeight-height-80,point.y-100))+'px';}
function screenPoint(p){const matrix=$('city-map').getScreenCTM();return matrix?new DOMPoint(p.x,p.y).matrixTransform(matrix):{x:innerWidth/2,y:innerHeight/2};}
function openInfo(content){const heading=content.querySelector('h2');if(heading){heading.id='info-title';$('info-dialog').setAttribute('aria-labelledby','info-title');}$('info-content').replaceChildren(content);if(!$('info-dialog').open)$('info-dialog').showModal();}
function showPlayer(p){
 const content=el('div');content.append(el('h2','',p.name+' ยท เธเธตเธงเธดเธ•เนเธเน€เธกเธทเธญเธ'));const education={m3:'เธก.3',highschool:'เธก.6',vocational:'เธเธงเธ.',diploma:'เธเธงเธช.',bachelor:'เธเธฃเธดเธเธเธฒเธ•เธฃเธต'},career=id=>state.catalog.careers.find(c=>c.id===id)?.name||'เธขเธฑเธเนเธกเนเธกเธต',list=el('div','detail-list');
 for(const[label,value]of[['เน€เธเธดเธเธชเธ”',money(p.cash)],['เธซเธเธตเน',money(p.debt)],['เธเธฒเธฃเธจเธถเธเธฉเธฒ',education[p.education.level]],['เธซเธเนเธงเธขเธเธดเธ•',amount(p.education.credits)],['เธเธฒเธเธซเธฅเธฑเธ',career(p.mainJobId)],['เธเธฒเธฃเนเธ•เนเธ—เธกเน',career(p.parttimeJobId)],['เธเธฃเธฐเธชเธเธเธฒเธฃเธ“เน',p.experience],['เธฃเธ–เธชเนเธงเธเธ•เธฑเธง',p.ownsCar?'เธกเธตเนเธฅเนเธง':'เธขเธฑเธเนเธกเนเธกเธต']]){const row=el('div');row.append(el('small','',label),el('strong','',value));list.append(row);}content.append(list);
 if(p.id===state.you.id&&state.offers?.length){content.append(el('h3','','เธเนเธญเน€เธชเธเธญเธเธฒเธเธ—เธตเนเธฃเธญเธเธฒเธฃเธ•เธญเธเธฃเธฑเธ'));for(const jobId of state.offers){const job=state.catalog.careers.find(j=>j.id===jobId);if(job){const row=el('div','catalog-item');row.append(el('strong','',job.name),el('small','',`Workday เธฟ${amount(job.payByPhase.workday)} / Weekend เธฟ${amount(job.payByPhase.weekend)}`),button('เธฃเธฑเธเธเธฒเธ '+job.name,'primary',()=>{action('accept_job',{jobId});$('info-dialog').close();}));content.append(row);}}}
 if(p.id===state.you.id){content.append(el('h3','','เธเธฒเธฃเนเธ”เธ•เนเธญเน€เธเธทเนเธญเธเธ—เธตเนเนเธเนเธญเธขเธนเน'));for(const card of state.passives)content.append(el('p','',card.name+' ยท เธ•เนเธญเธญเธฒเธขเธธ '+money(card.monthlyFee)+'/เน€เธ”เธทเธญเธ'));if(!state.passives.length)content.append(el('p','','เธขเธฑเธเนเธกเนเธกเธตเธเธฒเธฃเนเธ”เธ•เนเธญเน€เธเธทเนเธญเธ'));}openInfo(content);
}
function showDeck(){const content=el('div'),starter=state.players.find(p=>p.id===state.startingPlayerId);content.append(el('h2','','เธเธญเธเธเธฑเนเธงเธเธฅเธฒเธ'),el('p','','เธเธญเธเธเธตเนเนเธเนเธฃเนเธงเธกเธเธฑเธเธ—เธธเธเธเธ ยท เน€เธซเธฅเธทเธญ '+state.deck.remaining+'/'+state.deck.size+' เนเธ ยท เธเธญเธเธ—เธดเนเธ '+state.deck.discardCount+' เนเธ'),el('p','','เน€เธเธกเธชเธธเนเธกเธเธนเนเน€เธฅเนเธเน€เธฃเธดเนเธกเธเนเธญเธ เนเธฅเนเธงเนเธเธเธเธเธฅเธฐ 5 เนเธเธ•เธฒเธกเธฅเธณเธ”เธฑเธ เธเธนเนเน€เธฅเนเธเธเธฐเน€เธ•เธดเธกเธกเธทเธญเนเธซเนเธเธฃเธ 5 เนเธเธญเธฑเธ•เนเธเธกเธฑเธ•เธดเน€เธกเธทเนเธญเธเธ Weekend เธชเนเธงเธเธเธฒเธฃเธชเธธเนเธกเธ—เธตเนเธซเนเธฒเธเน€เธเนเธเธเธฒเธฃเธเธทเนเธญเน€เธเธดเนเธกเธเธฒเธเธเธญเธเน€เธ”เธตเธขเธงเธเธฑเธ'),el('p','panel-note','เธเธนเนเน€เธฃเธดเนเธกเน€เธเธก: '+(starter?.name||'-')+' ยท เธกเธทเธญเธชเธนเธเธชเธธเธ” 9 เนเธ ยท เน€เธกเธทเนเธญเธเธญเธเธซเธกเธ”เธเธฐเธชเธฑเธเธเธญเธเธ—เธดเนเธเธเธฅเธฑเธเธกเธฒ'));openInfo(content);}
function showRoom(){
 const content=el('div');content.append(el('h2','','เธซเนเธญเธ '+state.roomCode),el('p','',(state.mode==='season'?'Season':'Marathon')+' ยท เน€เธเนเธฒเธซเธกเธฒเธข '+money(state.goal)),button('เธเธฑเธ”เธฅเธญเธเธฃเธซเธฑเธชเธซเนเธญเธ','secondary',copyCode));
 for(const p of state.players){const row=el('div','info-player');row.append(avatar(p),el('span','',p.name+(p.id===state.you.id?' (เธเธธเธ“)':'')+(p.connected?'':' ยท เธญเธญเธเนเธฅเธเน')));content.append(row);}
 const audioSection=el('div');audioSection.append(el('h3','','เน€เธชเธตเธขเธ'));
 const sfxRow=el('div','audio-row');const sfxLabel=el('label','','Sound Effect');const sfxSlider=el('input');sfxSlider.type='range';sfxSlider.min='0';sfxSlider.max='100';sfxSlider.value=String(Math.round(_sfxVol*100));sfxSlider.addEventListener('input',()=>{_sfxVol=Number(sfxSlider.value)/100;if(_sfxGain)_sfxGain.gain.value=_sfxMuted?0:_sfxVol;localStorage.setItem('dt-sfx-vol',sfxSlider.value);});const sfxMuteBtn=button(_sfxMuted?'๐”':'๐”','subtle',()=>{_sfxMuted=!_sfxMuted;sfxMuteBtn.textContent=_sfxMuted?'๐”':'๐”';if(_sfxGain)_sfxGain.gain.value=_sfxMuted?0:_sfxVol;localStorage.setItem('dt-sfx-muted',_sfxMuted?'1':'0');});sfxRow.append(sfxLabel,sfxSlider,sfxMuteBtn);
 const bgmRow=el('div','audio-row');const bgmLabel=el('label','','Sound Background');const bgmSlider=el('input');bgmSlider.type='range';bgmSlider.min='0';bgmSlider.max='100';bgmSlider.value=String(Math.round(_bgmVol*100));bgmSlider.addEventListener('input',()=>{_bgmVol=Number(bgmSlider.value)/100;if(_bgmAudio)_bgmAudio.volume=_bgmMuted?0:_bgmVol;localStorage.setItem('dt-bgm-vol',bgmSlider.value);});const bgmMuteBtn=button(_bgmMuted?'๐”':'๐”','subtle',()=>{_bgmMuted=!_bgmMuted;bgmMuteBtn.textContent=_bgmMuted?'๐”':'๐”';if(_bgmAudio)_bgmAudio.volume=_bgmMuted?0:_bgmVol;localStorage.setItem('dt-bgm-muted',_bgmMuted?'1':'0');});bgmRow.append(bgmLabel,bgmSlider,bgmMuteBtn);
 audioSection.append(sfxRow,bgmRow);content.append(audioSection);
 const label=el('label','motion-setting'),check=el('input');check.type='checkbox';check.checked=motionOff;check.addEventListener('change',()=>{motionOff=check.checked;localStorage.setItem('downtown-motion-off',motionOff?'1':'0');renderHUD();});label.append(check,el('span','','เธฅเธ”เธเธฒเธฃเน€เธเธฅเธทเนเธญเธเนเธซเธง'));content.append(label,el('p','panel-note','เน€เธฃเธดเนเธก Phase เธ—เธตเนเธญเธเธฒเธฃเนเธ•เน€เธกเธเธ•เนเธ”เนเธงเธข 24 AP ยท เน€เธฅเธทเธญเธเธเธดเธเน€เธญเธเนเธฅเธฐเธเธฅเธฑเธเธเนเธฒเธเธเธญเธเธญเธขเนเธฒเธเธเนเธญเธข 4 AP ยท เน€เธ•เธดเธกเธเธฒเธฃเนเธ”เธเธ Weekend'));
 if(state.status==='playing'&&!me()?.surrendered){let step=0;const surrBtn=button('เธขเธญเธกเนเธเนเธ•เนเธญเธเธตเธงเธดเธ•เธญเธฑเธเธเนเธฒเธฃเธฑเธเธ—เธ”','exit-button',()=>{if(step===0){step=1;surrBtn.textContent='เธขเธทเธเธขเธฑเธเธเธฒเธฃเธขเธญเธกเนเธเน (เธเธ”เธญเธตเธเธเธฃเธฑเนเธ)';}else{$('info-dialog').close();socket.emit('game:surrender',{},()=>{});step=0;}});content.append(surrBtn);}
 if(state.status==='finished')content.append(button('เธ”เธนเธญเธฑเธเธ”เธฑเธ','primary',showResults));
 openInfo(content);
}
async function copyCode(){try{await navigator.clipboard.writeText(state.roomCode);notice('เธเธฑเธ”เธฅเธญเธเธฃเธซเธฑเธช '+state.roomCode+' เนเธฅเนเธง',true);}catch{notice('เธฃเธซเธฑเธชเธซเนเธญเธ: '+state.roomCode,true);}}
function endPhase(){if(state.status==='finished')return showResults();if(!myTurn()||busy())return;const p=me();if(p.custody)return action('serve_jail');if(p.sleepAp<4){const content=el('div');content.append(el('h2','','เธขเธฑเธเธเธญเธเนเธกเนเธเธฃเธ 4 AP'),el('p','','เธ–เนเธฒเธเธเธเนเธงเธเธ•เธญเธเธเธตเน เธเนเธงเธเธ–เธฑเธ”เนเธเธเธฐเน€เธชเธตเธขเน€เธงเธฅเธฒ 12โ€“18 AP เธเธฅเธฑเธเธญเธเธฒเธฃเนเธ•เน€เธกเธเธ•เนเนเธฅเนเธงเน€เธฅเธทเธญเธเธเธญเธเธเนเธญเธ'),button('เธเธเธเนเธงเธเธ•เนเธญเนเธ','secondary',()=>action('end_phase')),button('เธเธฅเธฑเธเนเธเธเธญเธ','subtle',()=>{$('info-dialog').close();chooseLocation('home');}));openInfo(content);}else action('end_phase');}
function showResults(){if(!state?.scoreboard)return;const content=el('div');content.append(el('h2','','เธชเธฃเธธเธเธเธตเธงเธดเธ•เนเธเน€เธกเธทเธญเธ'),el('p','','เน€เธเนเธเน€เธเธดเธเธชเธธเธ—เธเธดเธ–เธถเธเน€เธเนเธฒเธเนเธญเธเธเธเธฐ เธซเธฒเธเธเธฃเธเธเธณเธซเธเธ”เธเธฐเน€เธ—เธตเธขเธเธเธฐเนเธเธเธ—เธฑเนเธเธชเธตเนเธ”เนเธฒเธ'));for(const entry of state.scoreboard){const row=el('div','score-row'),copy=el('div');copy.append(el('strong','',entry.name),el('small','',Object.keys(statLabels).map(k=>statLabels[k]+' '+amount(entry[k])).join(' ยท ')),el('small','','เน€เธเธดเธเธชเธธเธ—เธเธด '+money(entry.netSavings)));row.append(el('b','',entry.rank),copy,el('strong','',amount(entry.total)+' เธเธฐเนเธเธ'));content.append(row);}content.append(button('Go to lobby','primary',leaveRoom));openInfo(content);}
const pause=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function animateElement(element,keyframes,options){if(reduced())return Promise.resolve();return element.animate(keyframes,options).finished.catch(()=>{});}
function sceneType(event){if(event.moneyLoss>0)return'money_loss';if(['opening_deal','discard_card'].includes(event.type))return'draw_card';if(event.type==='activity'){if(['market','convenience','restaurant'].includes(event.locationId))return'eat';if(event.locationId==='fitness')return'fitness';if(event.locationId==='hospital')return'heal';return'recreation';}return event.type;}
async function present(event){
 if(event.type==='opening_deal')return animateOpeningDeal(event);if(event.type==='travel'){await animateTravel(event);if(event.entryLoss||event.eventId)await present({...event,type:'travel_outcome',text:event.entryLoss?'เธ•เธฅเธฒเธ”เธกเธทเธ” ยท เธชเธธเธเธ เธฒเธ -'+event.entryLoss.health+' / เธเธงเธฒเธกเธชเธธเธ -'+event.entryLoss.happiness:event.text});return;}if(event.type==='draw_card'||(event.type==='discard_card'&&!state.deck.pendingDiscard)||event.refillCount>0)await flyCards(event.actorId,event.refillCount||1);
 const scene=$('scene-overlay'),night=['sleep','full_rest','emergency_rest'].includes(event.type);$('game-view').classList.toggle('night',night);scene.className='scene-overlay'+(night?' night':'')+(event.moneyLoss>0?' money-loss':'');$('scene-art').innerHTML=art().actionScene(sceneType(event),{color:state.players.find(p=>p.id===event.actorId)?.color});$('scene-label').textContent=event.text||'เธเธตเธงเธดเธ•เนเธเน€เธกเธทเธญเธ';$('scene-rewards').replaceChildren();
 for(const[key,value]of Object.entries(event.rewards||{})){if(!value)continue;const chip=el('span','reward-chip'+(value<0?' negative':''),(key==='cash'?'เน€เธเธดเธ':key==='ap'?'AP':statLabels[key]||key)+' '+(value>0?'+':'')+amount(value)+(key==='cash'?' เธฟ':''));chip.style.animationDelay=($('scene-rewards').children.length*.09)+'s';$('scene-rewards').append(chip);}scene.hidden=false;scene.setAttribute('popover','manual');scene.showPopover();if(myTurn()){await new Promise(r=>{let t=setTimeout(r,reduced()?100:event.moneyLoss>0?2200:560);document.addEventListener('click',()=>{clearTimeout(t);r();},{once:true,capture:true});});}else{await pause(reduced()?100:2000);}scene.hidePopover();scene.hidden=true;$('game-view').classList.remove('night');
 if(event.phaseNotices?.length)await present({type:'phase_notice',actorId:event.nextPlayerId||event.actorId,text:event.phaseNotices.join(' ยท ')});
 if(event.moneyLoss>0&&event.type!=='money_loss')await present({type:'money_loss',actorId:event.nextPlayerId||event.actorId,text:'เน€เธซเธ•เธธเธเธฒเธฃเธ“เนเน€เธชเธตเธขเน€เธเธดเธ '+money(event.moneyLoss),moneyLoss:event.moneyLoss,rewards:{cash:-event.moneyLoss}});
 if(event.completedPhase){if(event.completedPhase==='weekend')await present({type:'turn_end',actorId:event.actorId,text:'เธเธเธ•เธฒเธเธญเธ '+event.actorName+' ยท Turn '+event.completedWeek});if(event.nextPlayerId)await present({type:'turn_start',actorId:event.nextPlayerId,text:(event.completedPhase==='weekend'?'เน€เธฃเธดเนเธกเธ•เธฒเธเธญเธ ':'Phase 2/2 ยท ')+event.nextPlayerName+' ยท Turn '+event.nextWeek});}
 if(event.applicationResults?.length)for(const result of event.applicationResults){const job=state.catalog.careers.find(j=>j.id===result.jobId),place=locations().find(l=>l.id===job?.locationId);const rejText=`โ เนเธกเนเธเนเธฒเธ: ${job?.name} (เนเธญเธเธฒเธช ${Math.round((result.chance||0)*100)}%)`;await present({type:'apply_job',actorId:event.nextPlayerId||event.actorId,text:result.accepted?'เนเธ”เนเธเนเธญเน€เธชเธเธญเธเธฒเธเธ—เธตเน '+(place?.name||'')+' ยท '+(job?.name||'')+' ยท เนเธเธฃเธฑเธเธเธฒเธเธ—เธตเน เธชเธณเธเธฑเธเธเธฒเธเธเธฑเธ”เธซเธฒเธเธฒเธ!':rejText});}
}
async function flyCards(playerId,count=1){
 if(reduced()||count<1)return;const deck=$('deck-dock').getBoundingClientRect(),start={x:deck.left+deck.width/2,y:deck.top+deck.height/2};let target;
 if(playerId===state.you.id){const hand=document.querySelector('.hand-area').getBoundingClientRect();target={x:hand.left+hand.width*.55,y:hand.top+Math.min(70,hand.height*.5)};}
 else{const token=$('rivals').querySelector('[data-player="'+playerId+'"]')?.getBoundingClientRect();target=token?{x:token.left+token.width/2,y:token.top+token.height/2}:{x:innerWidth/2,y:innerHeight-80};}
 const flights=[];for(let index=0;index<count;index+=1){const card=el('div','flying-card');card.style.left='0px';card.style.top='0px';$('motion-layer').append(card);flights.push(animateElement(card,[{transform:`translate(${start.x-40}px,${start.y-90}px) rotate(-8deg) scale(.55)`,opacity:0},{transform:`translate(${start.x-40}px,${start.y-145}px) rotate(5deg) scale(.82)`,opacity:1,offset:.3},{transform:`translate(${target.x-42+index*4}px,${target.y-58-index*2}px) rotate(${index*3-6}deg) scale(.48)`,opacity:0}],{duration:560,delay:index*90,easing:'ease-in-out',fill:'both'}).finally(()=>card.remove()));}await Promise.all(flights);
}
async function animateOpeningDeal(event){
 const tip=$('map-tip'),handSize=event.startingHandSize||5;for(const playerId of event.order||[]){const player=state.players.find(p=>p.id===playerId);tip.textContent='เธเธณเธฅเธฑเธเนเธเธ '+handSize+' เนเธเนเธซเน '+(player?.name||'เธเธนเนเน€เธฅเนเธ');await flyCards(playerId,handSize);}
 const starter=state.players.find(p=>p.id===event.startingPlayerId);tip.textContent=(starter?.name||'เธเธนเนเน€เธฅเนเธเนเธฃเธ')+' เน€เธฃเธดเนเธก Turn เนเธฃเธเธ”เนเธงเธขเธเธฒเธฃเนเธ” 5 เนเธ';notice((starter?.name||'เธเธนเนเน€เธฅเนเธเนเธฃเธ')+' เนเธ”เนเน€เธฃเธดเนเธกเธเนเธญเธเธ”เนเธงเธขเธเธฒเธฃเนเธ” 5 เนเธ',true);
}
function vehicle(transport,color){
 if(transport==='moto')return'<g class="vehicle-token"><ellipse cy="5" rx="24" ry="6" fill="#35494b20"/><circle cx="-17" r="7" fill="#635a64"/><circle cx="19" r="7" fill="#635a64"/><path d="M-17 0L-6 -15L10 -4H19L13 -24" fill="none" stroke="#aa93ae" stroke-width="6" stroke-linecap="round"/><path d="M-9 -16L5 -16" stroke="#635a64" stroke-width="4"/><path d="M-5 -18L-2 -33L11 -25" fill="none" stroke="'+color+'" stroke-width="8" stroke-linecap="round"/><circle cx="0" cy="-42" r="8" fill="#edc6a5" stroke="#635a64"/><path d="M-9 -42Q-8 -55 3 -52Q9 -48 8 -42" fill="#a8bbc3" stroke="#635a64"/></g>';
 const fill=transport==='bus'?'#89b2be':transport==='taxi'?'#dfc480':color,bus=transport==='bus';return'<g class="vehicle-token"><ellipse cy="5" rx="'+(bus?32:23)+'" ry="7" fill="#35494b20"/><rect x="'+(bus?-33:-25)+'" y="'+(bus?-32:-23)+'" width="'+(bus?66:50)+'" height="'+(bus?32:23)+'" rx="7" fill="'+fill+'" stroke="#635a64" stroke-width="2"/><rect x="'+(bus?-25:-15)+'" y="'+(bus?-28:-20)+'" width="'+(bus?48:27)+'" height="'+(bus?14:11)+'" rx="3" fill="#d4e3df" stroke="#635a64" stroke-width="1.5"/><circle cx="-17" cy="0" r="5" fill="#635a64"/><circle cx="18" cy="0" r="5" fill="#635a64"/><path d="M0 '+(bus?-28:-20)+'v'+(bus?14:11)+(bus?'M-12 -28v14M12 -28v14':'')+'" stroke="#635a64" stroke-width="1.5"/><circle cx="'+(bus?29:22)+'" cy="-10" r="2" fill="#fff5ce"/>'+(transport==='taxi'?'<rect x="-9" y="-30" width="18" height="7" rx="2" fill="#fff5ce" stroke="#635a64"/><text x="0" y="-25" text-anchor="middle" font-size="5" fill="#635a64">TAXI</text>':'')+'</g>';
}
async function animateTravel(event){
 const canvas=$('city-map'),player=state.players.find(p=>p.id===event.actorId);if(!player)return;const target=canvas.querySelector('[data-player="'+event.actorId+'"]');if(target)target.style.opacity='0';const token=svg('g'),route=svg('polyline',{points:points(event.path||[]),class:'map-route'});canvas.append(route,token);
 try{const legs=(event.legs?.length?event.legs:[{transport:event.transport,path:event.path}]).filter(l=>l.path?.length>1),total=legs.reduce((n,l)=>n+l.path.length-1,0);for(const leg of legs){token.setAttribute('class','travel-token'+(leg.transport==='walk'?' token-walking':''));token.innerHTML=leg.transport==='walk'?art().token(player.color,state.players.indexOf(player)):vehicle(leg.transport,player.color);const duration=reduced()?0:Math.max(180,Math.min(1900,450+total*22)*(leg.path.length-1)/total);await moveAlong(token,leg.path,duration);}notice(player.name+' เธ–เธถเธ'+(labels[event.locationId]||'เธเธธเธ”เธซเธกเธฒเธข')+' ยท '+amount(-(event.rewards?.ap||0))+' AP'+(event.rewards?.cash?' ยท '+money(event.rewards.cash):''),true);}finally{token.remove();route.remove();if(target)target.style.opacity='';}
}
function moveAlong(token,path,duration){const positions=path.map(at);if(!positions.length)return Promise.resolve();if(!duration){const p=positions.at(-1);token.setAttribute('transform',`translate(${p.x} ${p.y})`);return Promise.resolve();}return new Promise((resolve,reject)=>{let start;function frame(now){try{start??=now;const progress=Math.max(0,Math.min(1,(now-start)/duration)),scaled=progress*(positions.length-1),index=Math.min(positions.length-2,Math.floor(scaled)),fraction=scaled-index,a=positions[index],b=positions[index+1];token.setAttribute('transform',`translate(${a.x+(b.x-a.x)*fraction} ${a.y+(b.y-a.y)*fraction})`);if(progress<1)requestAnimationFrame(frame);else resolve();}catch(error){reject(error);}}requestAnimationFrame(frame);});}
async function drain(){if(animating)return;animating=true;renderHUD();renderCards();try{while(queue.length&&state)await present(queue.shift());}catch(error){console.error('Presentation error',error);}finally{animating=false;$('scene-overlay').hidden=true;$('game-view').classList.remove('night');if(state&&state.status!=='lobby')renderMap();renderHUD();renderCards();if(selected)renderLocation();if(state?.status==='finished'&&!resultsShown){resultsShown=true;showResults();}}}
function onState(next){if(!next?.you)return;const prior=state,opening=prior?.status==='lobby'&&next.status==='playing'&&next.openingDeal;state=next;saveRoom(next);const event=next.lastPresentation,isNew=event?.id!==lastPresentation;if(event)lastPresentation=event.id;if(opening){setHand(true);queue.push({...next.openingDeal,type:'opening_deal'});if(event)queue.push(event);}else if(prior&&isNew&&event){if(event.actorId===next.you.id&&['draw_card','play_card','discard_card'].includes(event.type)||event.actorId===next.you.id&&event.refillCount>0)setHand(true);queue.push(event);}render();if(queue.length)drain();}
async function enter(event,payload){if(requestPending||!socket.connected)return;const name=$('player-name').value.trim();if(!name){$('player-name').focus();return notice('เนเธชเนเธเธทเนเธญเธ•เธฑเธงเธฅเธฐเธเธฃเธเนเธญเธเน€เธเนเธฒเน€เธกเธทเธญเธ');}requestPending=true;try{const reply=await socket.timeout(7000).emitWithAck(event,{name,...payload});if(!reply.ok)notice(reply.error);else saveRoom(reply);}catch{notice('เน€เธเธทเนเธญเธกเธ•เนเธญเธซเนเธญเธเนเธกเนเนเธ”เน เธเธฃเธธเธ“เธฒเธฅเธญเธเธญเธตเธเธเธฃเธฑเนเธ');}finally{requestPending=false;render();}}
$('create-form').addEventListener('submit',e=>{e.preventDefault();enter('room:create',{mode:$('game-mode').value,singlePlayer:$('play-mode').value==='solo'});});$('join-form').addEventListener('submit',e=>{e.preventDefault();enter('room:join',{code:$('room-code-input').value.trim().toUpperCase()});});$('start-game').addEventListener('click',()=>perform('game:start',{code:state.roomCode}));$('copy-code').addEventListener('click',copyCode);$('room-menu').addEventListener('click',showRoom);$('details-button').addEventListener('click',()=>showPlayer(me()));$('close-location').addEventListener('click',closeLocation);$('close-info').addEventListener('click',()=>$('info-dialog').close());$('end-phase').addEventListener('click',endPhase);$('hand-toggle').addEventListener('click',()=>setHand(document.querySelector('.hand-area').classList.contains('collapsed')));
$('info-dialog').addEventListener('cancel',e=>e.preventDefault());$('info-dialog').addEventListener('click',e=>{if(e.target===$('info-dialog'))$('info-dialog').close();});addEventListener('resize',()=>{if(selected)positionPanel(locations().find(l=>l.id===selected));});
// R3: click outside location panel closes it
document.addEventListener('click', e => {
  const panel = $('location-panel');
  if (panel && !panel.hidden && !panel.contains(e.target) && !e.target.closest('.map-location') && !e.target.closest('.hand-card')) {
    closeLocation();
  }
});
$('exit-room').addEventListener('click',askToLeave);$('deck-dock').addEventListener('click',showDeck);$('working-button').addEventListener('click',()=>{const work=state.actions.find(a=>a.type==='work');if(work)action(work.type,work.payload);else{const job=state.catalog.careers.find(j=>j.id===me().mainJobId||j.id===me().parttimeJobId);if(job)chooseLocation(job.locationId);}});
$('hero-faces').innerHTML=['#d87e72','#86aaa0','#9c93ba','#d9ac67'].map((color,index)=>art().avatar(color,index)).join('');
if(typeof window.io!=='function'){connection('เนเธซเธฅเธ”เธเธฒเธฃเน€เธเธทเนเธญเธกเธ•เนเธญเนเธกเนเนเธ”เน',true);notice('เน€เธเธดเธ”เน€เธเธกเธเนเธฒเธเน€เธเธดเธฃเนเธเน€เธงเธญเธฃเนเธเธญเธเน€เธ”เนเธก');return;}
socket=window.io();socket.on('game:state',onState);socket.on('room:closed',({roomCode})=>{if(state?.roomCode===roomCode)returnToLanding('เนเธฎเธชเธ•เนเธขเธเน€เธฅเธดเธเธซเนเธญเธเนเธฅเนเธง เธชเธฃเนเธฒเธเธซเธฃเธทเธญเน€เธเนเธฒเธซเนเธญเธเนเธซเธกเนเนเธ”เนเน€เธฅเธข');});socket.on('connect',async()=>{if(tabReplaced)return;connection('เน€เธเธทเนเธญเธกเธ•เนเธญเนเธฅเนเธง');const room=readRoom();if(room){try{const reply=await socket.timeout(7000).emitWithAck('room:resume',{code:room.roomCode,playerId:room.playerId});if(!reply.ok){returnToLanding('เธซเนเธญเธเน€เธ”เธดเธกเธเธดเธ”เนเธฅเนเธง เธชเธฃเนเธฒเธเธซเธฃเธทเธญเน€เธเนเธฒเธซเนเธญเธเนเธซเธกเนเนเธ”เนเน€เธฅเธข');}}catch{notice('เธเธฅเธฑเธเน€เธเนเธฒเธซเนเธญเธเน€เธ”เธดเธกเนเธกเนเนเธ”เน เธเธฃเธธเธ“เธฒเธฅเธญเธเนเธซเธฅเธ”เนเธซเธกเน');}}});socket.on('room:replaced',()=>{tabReplaced=true;queue=[];selected='';requestPending=false;state=null;$('info-dialog').close();$('location-panel').hidden=true;socket.disconnect();connection('เน€เธเธกเธขเนเธฒเธขเนเธเนเธ—เนเธเธญเธทเนเธ',true);render();notice('เธ•เธฑเธงเธฅเธฐเธเธฃเธเธตเนเน€เธเธดเธ”เนเธเนเธ—เนเธเธญเธทเนเธเนเธฅเนเธง เน€เธฅเนเธเธ•เนเธญเธ—เธตเนเนเธ—เนเธเธเธฑเนเธ เธซเธฃเธทเธญเนเธซเธฅเธ”เธซเธเนเธฒเธเธตเนเนเธซเธกเนเน€เธเธทเนเธญเธเธฅเธฑเธเธกเธฒ');});socket.on('disconnect',()=>{if(tabReplaced)return;connection('เธเธณเธฅเธฑเธเน€เธเธทเนเธญเธกเธ•เนเธญเนเธซเธกเน',true);requestPending=false;notice('เธเธฒเธฃเน€เธเธทเนเธญเธกเธ•เนเธญเธซเธฅเธธเธ” เธเธณเธฅเธฑเธเธเธฅเธฑเธเน€เธเนเธฒเธซเนเธญเธเน€เธ”เธดเธก');});socket.on('connect_error',()=>connection('เน€เธเธทเนเธญเธกเธ•เนเธญเนเธกเนเนเธ”เน',true));render();
let _turnDeadline = 0;
socket.on('game:timer', (data) => {
  _turnDeadline = data.turnDeadline || 0;
});
setInterval(() => { 
  if (!state) return; 
  let timerLabel = document.getElementById('turn-timer');
  if (!timerLabel) {
    const pName = document.querySelector('.player-name, [data-player]'); // attempt to find where to append it, but it's better to just inject into the header
    const header = document.querySelector('header');
    if (header && !document.getElementById('turn-timer')) {
      timerLabel = document.createElement('span');
      timerLabel.id = 'turn-timer';
      timerLabel.style.marginLeft = '10px';
      timerLabel.style.fontWeight = 'bold';
      timerLabel.style.color = '#ff6b6b';
      header.appendChild(timerLabel);
    }
  }
  if (!timerLabel) return; 
  let remaining = 0; 
  if (_turnDeadline) remaining = Math.max(0, Math.ceil((_turnDeadline - Date.now()) / 1000));
  if (remaining > 0) timerLabel.textContent = ' ⏱ ' + remaining + 's'; 
  else timerLabel.textContent = ''; 
}, 1000);
})();
