import { mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const artifactDir = process.env.DOWNTOWN_UI_ARTIFACTS || join(tmpdir(), 'downtown-ui-smoke-'+Date.now());
mkdirSync(artifactDir,{recursive:true});
import assert from 'node:assert/strict';
import { createGameServer } from '../server/index.js';
const game=createGameServer(); await new Promise(resolve=>game.httpServer.listen(0,'127.0.0.1',resolve));
const baseUrl='http://127.0.0.1:'+game.httpServer.address().port;
let browser;
try { browser=await chromium.launch({headless:true,timeout:15000,...(process.env.PLAYWRIGHT_BROWSER_CHANNEL?{channel:process.env.PLAYWRIGHT_BROWSER_CHANNEL}:{})}); }
catch(error){await new Promise(resolve=>game.io.close(resolve));game.httpServer.close();throw error;}
const errors=[];
const capture=()=>{let original;Object.defineProperty(window,'io',{configurable:true,get(){return original;},set(fn){original=(...args)=>{const socket=fn(...args);window.qaSocket=socket;socket.on('game:state',s=>window.qaState=s);return socket;};}});};
const c1=await browser.newContext({viewport:{width:1600,height:1000}}),c2=await browser.newContext({viewport:{width:1600,height:1000},reducedMotion:'reduce'});
await c1.addInitScript(capture);await c2.addInitScript(capture);const p1=await c1.newPage(),p2=await c2.newPage();for(const p of[p1,p2])p.on('pageerror',error=>errors.push(error.message));
const ready=p=>p.waitForFunction(()=>window.qaState?.status==='playing'&&!document.querySelector('#end-phase').disabled,{},{timeout:15000});

async function openVenue(page,id){if(await page.locator('#info-dialog').evaluate(d=>d.open))await page.click('#close-info');if(await page.locator('#location-panel').isVisible())await page.click('#close-location');await page.locator('[data-location="'+id+'"]').click();}
try{
 await Promise.all([p1.goto(baseUrl),p2.goto(baseUrl)]);await p1.screenshot({path:join(artifactDir,'landing-v2-preview.png')});
 await p1.fill('#player-name','Solo host');await p1.click('#create-form button');await p1.waitForSelector('#waiting-view',{state:'visible'});
 await p1.click('#exit-room');await p1.waitForSelector('#landing-view',{state:'visible'});assert.equal(game.rooms.size,0);assert.equal(await p1.evaluate(()=>localStorage.getItem('downtown-local-room-v1')),null);
 await p1.reload();await p1.waitForFunction(()=>window.qaSocket?.connected);assert.equal(await p1.locator('#waiting-view').isVisible(),false);
 await p1.fill('#player-name','Apiwit');await p1.click('#create-form button');await p1.waitForFunction(()=>window.qaState?.roomCode);
 let code=await p1.evaluate(()=>window.qaState.roomCode);await p2.fill('#player-name','Mali');await p2.fill('#room-code-input',code);await p2.click('#join-form button');await p1.waitForFunction(()=>window.qaState.players.length===2);
 await p2.click('#exit-room');await p2.waitForSelector('#landing-view',{state:'visible'});await p1.waitForFunction(()=>window.qaState.players.length===1);assert.equal(await p1.locator('#start-game').isDisabled(),true);assert.equal(await p2.evaluate(()=>localStorage.getItem('downtown-local-room-v1')),null);
 await p2.click('#join-form button');await p1.waitForFunction(()=>window.qaState.players.length===2);await p1.click('#exit-room');await p1.waitForSelector('#info-dialog[open]');await p1.screenshot({path:join(artifactDir,'exit-lobby-preview.png')});await p1.locator('#info-dialog .exit-button').click();await Promise.all([p1.waitForSelector('#landing-view',{state:'visible'}),p2.waitForSelector('#landing-view',{state:'visible'})]);assert.equal(game.rooms.size,0);
 for(const p of[p1,p2])assert.equal(await p.evaluate(()=>localStorage.getItem('downtown-local-room-v1')),null);
 await p1.click('#create-form button');await p1.waitForSelector('#waiting-view',{state:'visible'});code=await p1.evaluate(()=>window.qaState.roomCode);await p2.fill('#room-code-input',code);await p2.click('#join-form button');await p1.waitForFunction(()=>window.qaState.players.length===2);
 if(process.argv.includes('--lobby-only')){assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,checks:['solo host Exit','refresh does not restore canceled room','guest Exit/rejoin','host cancellation returns both players to start','create again in same browser'],browserErrors:errors,artifacts:artifactDir}));}
 else{
 game.rooms.get(code).rng=()=>0;
 await p1.click('#start-game');await ready(p1);assert.equal(await p1.locator('.hand-card').count(),5);assert.equal(await p1.locator('.map-location').count(),18);assert.equal(await p1.locator('#game-log').count(),0);
 const checkVenues=async()=>{const blocked=await p1.evaluate(()=>[...document.querySelectorAll('.map-location')].filter(g=>{const r=g.getBoundingClientRect();const hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return hit?.closest('.map-location')!==g;}).map(g=>g.getAttribute('data-location')));assert.deepEqual(blocked,[],'Every venue must remain clickable');};await checkVenues();await p1.screenshot({path:join(artifactDir,'demo-v2-preview.png')});await p1.click('#hand-toggle');await checkVenues();await p1.screenshot({path:join(artifactDir,'hand-v2-preview.png')});
 assert.equal(await p1.locator('.hand-card').count(),5);assert.equal(await p1.evaluate(()=>window.qaState.deck.size),52);assert.equal(await p1.evaluate(()=>window.qaState.startingPlayerId),await p1.evaluate(()=>window.qaState.you.id));
 await openVenue(p1,'bank');assert.equal(await p1.locator('.transport-row').count(),5);await p1.screenshot({path:join(artifactDir,'travel-v2-preview.png')});
 await p1.bringToFront();await p1.locator('.transport-row').filter({hasText:'แท็กซี่'}).click();await p1.waitForSelector('.travel-token');await p2.evaluate(()=>window.qaSocket.disconnect());await p1.waitForFunction(()=>window.qaState.players[1].connected===false);assert.equal(await p1.locator('.travel-token').count(),1,'State update must not remove a moving token');await p2.evaluate(()=>window.qaSocket.connect());await p1.waitForFunction(()=>window.qaState.players[0].locationId==='bank');await ready(p1);
 await openVenue(p1,'bank');await p1.locator('.action-button').filter({hasText:'กู้ ฿1000'}).click();await ready(p1);assert.equal(await p1.evaluate(()=>window.qaState.players[0].debt),1000);
 // Prepare a reproducible Skill hand in the isolated QA server, preserving deck conservation.
 const room=game.rooms.get(code),self=room.players[0];const putCardInHand=cardId=>{const sources=[room.deck,room.discard,...room.players.map(player=>player.hand)];for(const source of sources){const index=source.indexOf(cardId);if(index<0)continue;if(source===self.hand)return;[self.hand[0],source[index]]=[source[index],self.hand[0]];return;}assert.fail('Missing fixture card '+cardId);};putCardInHand('skill_fresh_start');
 await p1.evaluate(async()=>{await window.qaSocket.timeout(5000).emitWithAck('room:resume',{code:window.qaState.roomCode,playerId:window.qaState.you.id});});await ready(p1);
 if(await p1.locator('#hand-toggle').getAttribute('aria-expanded')==='false')await p1.click('#hand-toggle');const skill=await p1.evaluate(()=>window.qaState.hand.findIndex(c=>c.id==='skill_fresh_start'));if(await p1.locator('#info-dialog').evaluate(d=>d.open))await p1.click('#close-info');await p1.locator('.hand-card').nth(skill).click();await p1.locator('#info-dialog button').filter({hasText:'ใช้การ์ด'}).click();await p1.waitForFunction(()=>window.qaState.deck.pendingDiscard);await p1.waitForFunction(()=>!document.querySelector('.hand-card').disabled);assert.ok(await p1.locator('#end-phase').isDisabled());
 const countBefore=await p1.evaluate(()=>window.qaState.hand.length);if(await p1.locator('#info-dialog').evaluate(d=>d.open))await p1.click('#close-info');await p1.locator('.hand-card').first().click();await p1.locator('#info-dialog button').filter({hasText:'ทิ้งใบนี้'}).click();await p1.waitForFunction(()=>!window.qaState.deck.pendingDiscard);await ready(p1);assert.equal(await p1.evaluate(()=>window.qaState.hand.length),countBefore+1);
 await openVenue(p1,'home');await p1.locator('.transport-row').filter({hasText:'แท็กซี่'}).click();await ready(p1);
 await openVenue(p1,'home');await p1.locator('.action-button').filter({hasText:'นอน 4 AP'}).click();await ready(p1);assert.equal(await p1.evaluate(()=>window.qaState.players[0].sleepAp),4);
 await p1.click('#end-phase');await ready(p1);assert.match(await p1.locator('#phase-label').textContent(),/Phase 2\/2/);assert.equal(await p1.evaluate(()=>window.qaState.deck.refillToHandSize),5);
 await p1.setViewportSize({width:1280,height:720});if(await p1.locator('#location-panel').isVisible())await p1.click('#close-location');if(await p1.locator('#hand-toggle').getAttribute('aria-expanded')==='false')await p1.click('#hand-toggle');if(await p1.locator('#location-panel').isVisible())await p1.click('#close-location');await checkVenues();await p1.screenshot({path:join(artifactDir,'demo-v2-1280.png')});
 await p1.setViewportSize({width:390,height:844});await p1.screenshot({path:join(artifactDir,'demo-v2-mobile.png')});const sizes=await p1.evaluate(()=>({w:innerWidth,scroll:document.documentElement.scrollWidth}));assert.equal(sizes.scroll,sizes.w);
 await p1.setViewportSize({width:1600,height:1000});await p1.emulateMedia({reducedMotion:'reduce'});await openVenue(p1,'hospital');await p1.locator('.transport-row').filter({hasText:'วินมอเตอร์ไซค์'}).click();await ready(p1);assert.equal(await p1.evaluate(()=>document.getAnimations().length),0);await p1.emulateMedia({reducedMotion:'no-preference'});
 // Trigger a real goal-winning card action using an isolated test fixture.
 if(await p1.locator('#location-panel').isVisible())await p1.click('#close-location');self.cash=room.goal-100;putCardInHand('skill_overtime');
 await p1.evaluate(async()=>window.qaSocket.timeout(5000).emitWithAck('room:resume',{code:window.qaState.roomCode,playerId:window.qaState.you.id}));await ready(p1);if(await p1.locator('#hand-toggle').getAttribute('aria-expanded')==='false')await p1.click('#hand-toggle');const winCard=await p1.evaluate(()=>window.qaState.hand.findIndex(c=>c.id==='skill_overtime'));if(await p1.locator('#info-dialog').evaluate(d=>d.open))await p1.click('#close-info');await p1.locator('.hand-card').nth(winCard).click();await p1.locator('#info-dialog button').filter({hasText:'ใช้การ์ด'}).click();await p1.waitForFunction(()=>window.qaState.status==='finished'&&!document.querySelector('#scene-overlay').hidden);assert.equal(await p1.locator('#info-dialog').evaluate(d=>d.open),true);await p1.waitForTimeout(350);await p1.screenshot({path:join(artifactDir,'action-v2-preview.png')});await p1.waitForFunction(()=>document.querySelector('#info-dialog').open);
 // Reconnect in same context: old tab must relinquish its session visibly.
 const duplicate=await c1.newPage();duplicate.on('pageerror',error=>errors.push(error.message));await duplicate.goto(baseUrl);await duplicate.waitForFunction(()=>window.qaState?.phase==='weekend');await p1.waitForFunction(()=>document.querySelector('#connection-status').textContent.includes('แท็บอื่น'));
 assert.deepEqual(errors,[]);console.log(JSON.stringify({ok:true,checks:['2 players create/join/start','random starter fixture','5-card opening deal','52-card shared Season deck','18 venues no Log','5 transport previews','taxi travel','bank borrow','Skill discard/draw lock','home-only sleep scene','Phase 2/2 prepares Weekend refill','1280 and mobile layout','resume/tab replacement','all venues clickable with folded and expanded hand','state update during travel','reduced-motion travel with no animations','winning action scene before results'],browserErrors:errors,artifacts:artifactDir}));
}
}catch(error){console.log(JSON.stringify({error:String(error),browserErrors:errors,state:await p1.evaluate(()=>({phase:window.qaState?.phase,status:window.qaState?.status,active:window.qaState?.activePlayerId,you:window.qaState?.you,disabled:document.querySelector('#end-phase').disabled,scene:document.querySelector('#scene-label').textContent,notice:document.querySelector('#notice').textContent,animations:document.getAnimations().length,trip:window.qaState?.lastPresentation}))}));await p1.screenshot({path:join(artifactDir,'qa-failure-v2.png')});throw error;}finally{await browser.close();await new Promise(resolve=>game.io.close(resolve));game.httpServer.close();}
